WCOSS2 run support and script/config updates
NOAA-EMC/global-workflow pull request #1030
Opened 2022-09-22 17:37 UTC by KateFriedman-NOAA

**Description**

This PR includes script and run support updates for running the `develop` branch on WCOSS2. This PR does not include resource updates for running on WCOSS2 and does not complete the port to WCOSS2. Additional WCOSS2 `develop` port PRs will follow this PR.

Changes in this PR mostly address the following:

1. WCOSS2 port changes requested by NCO (e.g. `NWPROD`/`NWROOT` -> `PACKAGEROOT`) in the move of operations to WCOSS2 in the past year.
2. Adding WCOSS2 support in the way of creating `WCOSS2.env`, a `wcoss2.yaml` hosts file for rocoto, and config updates.
3. Some cleanup that was also done in the operations GFS port to WCOSS2.

More specifically, the changes in this PR are:

1. Create `WCOSS2.env` under the env folder.
2. Remove references/usage of jlogfile thoughout.
3. Change `NWPROD` to `PACKAGEROOT` throughout.
4. Replace `NWROOT` with `OPSROOT` where appropriate.
5. Env file updates (non-WCOSS2):
  * Update "anal" if block in `HERA.env` and `ORION.env` to add "or" for "analcalc"; needed to match similar setting in `WCOSS2.env` and change in `jobs/JGLOBAL_ATMOS_ANALYSIS_CALC`
6. Update JJOB scripts:
  * Update `jobs/JGLOBAL_ATMOS_ANALYSIS_CALC` to pass "analcalc" to env file instead of "anal"
  * Move config and env file sourcing from rocoto job scripts into JJOBs for gempak
  * Update the default COM* paths to utilize `compath.py` and the new `compath.py` format; includes updating `COMINukmet` and `COMINecmwf` defaults to new `compath.py` format
  * Add `COMINobsproc` to `jobs/JGFS_ATMOS_GEMPAK_NCDC_UPAPGIF`
  * Replace `COMINgfs` with `COMINobsproc` and replace `COMINgfs_m6hrs` with `COMIN_m6hrs` in `jobs/JGLOBAL_ATMOS_EMCSFC_SFC_PREP`
  * Update `ARCHSYND`, `HOMENHC` and `TANK_TROPCY` in `jobs/JGLOBAL_ATMOS_TROPCY_QC_RELOC`, remove `HOMENHCp1`
  * Update default `APRUN` commands for several downstream jobs (`mpirun` -> `mpiexec`)
  * Set `wavempexec` to `wavempexec` instead of `launcher` in `jobs/JGLOBAL_WAVE_INIT`
  * Correct list of configs to source in `jobs/JGLOBAL_WAVE_POST_BNDPNTBLL` to include `wavepostbndpntbll` instead `wavepostbndpnt`
  * Update how `PDY` is invoked (`. PDY` to `. ./PDY`)
  * Update the `RUN` and `RUN2` variables in `jobs/JGFS_ATMOS_GEMPAK_PGRB2_SPEC`
  * Some cleanup to remove unneeded `RUN_ENVIR=nco` checks and some extra whitespaces.
7. Update rocoto job scripts:
  * Move config and env sourcing out of gempak rocoto job scripts (moved to JJOB scripts); also change to invoke JJOB directly and add `exit $status`
  * Update `jobs/rocoto/prep.sh` to use new `HOMEobsproc` and `JOBSPROC_GLOBAL_PREP` JJOB script.
  * Update fit2obs and tracker section of `jobs/rocoto/vrfy.sh`
  * Add missing env file sourcing to `jobs/rocoto/wafsgcip.sh`
8. Update `module_base.wcoss2.lua` to use para version of `ncdiag` module (update to use official ops install later)
9. Updates to configs:
  * Whitespace cleanup in `config.anal`
  * Add `export nth_echgres=$nth_echgres_gfs` when CDUMP=gfs in `config.analcalc`
  * Add `COMINsyn` to `config.base.emc.dyn` and update obsproc package variables
  * Update `ROTDIR` in `config.base.nco.static`
  * Change `OUTPUT_FILETYPE_` variables to be "netcdf" on all machines in `config.efcs`
  * Updates to `config.fv3.nco.static`: remove non-WCOSS2 references, add `npe_node_max=128` for WCOSS2, change C384 DELTIM to 200 (ops value), and update variables for C384/C768 to ops values
  * Remove `GEMPAKSH=$HOMEgfs/jobs/JGFS_ATMOS_GEMPAK` line in `config.gempak`; now invoking `$HOMEgfs/jobs/JGFS_ATMOS_GEMPAK` directly in the JJOB
  * Update `COMINsyn` default in `config.prep` and `config.vrfy`
  * Create `config.resources.nco.static`, copy from `operations`; will need updating for GFSv17 opd
  * Tracker updates in `config.vrfy`
10. Updates to scripts:
  * Updates to `RUN` and `RUN2` variables in `scripts/exgdas_atmos_nawips.sh`, `scripts/exgfs_atmos_goes_nawips.sh`, and `scripts/exgfs_atmos_nawips.sh`
  * Replace `COMINgfs` with `COMINobsproc` in `scripts/exgfs_atmos_gempak_gif_ncdc_skew_t.sh`
  * Update `APRUN` in `scripts/exgfs_atmos_gempak_meta.sh` (`mpirun` -> `mpiexec`)
11. Update `sorc/link_workflow.sh` to also copy the appropriate versions of `config.fv3` and `config.resources` in NCO mode.
12. Updates to ush scripts:
  * Remove references to `NWPROD` and replace with appropriate variables or paths.
  * Add echos to `ush/gfs_bufr.sh` to print out the specific forecast hour files for SPAs to check in case of failure. (Added by GDIT and Bo Cui)
  * Delete `ush/global_extrkr.sh` (not used anywhere anymore).
13. Update util source codes to build with `ftn` and include `-g -traceback` `FFLAGS`
14. Updates to setup script files:
  * Replace `nwprod` with `packageroot` in hosts files and `setup_expt.py`.
  * Create `wcoss2.yaml` host file.
  * Update `workflow_tasks.py` to set native xml tag for pbspro.

Issue #419

**Type of change**

- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

- [x] Clone and build tests on WCOSS2, Hera, and Orion
- [x] Cycled atmos-only tests on WCOSS2, Hera, and Orion (C192C96L127 on all machines and C768C384L127 on WCOSS2)
- [x] Forecast-only coupled tests on Hera and Orion

No downstream/ops-only jobs were invoked in testing, however updates to those job scripts are included in this PR.
  
**Checklist**

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

2022-09-26 16:29 UTC, KateFriedman-NOAA commented
Tests on Hera and Orion have both now completed. Atmos-only cycled and forecast-only coupled tests using `feature/dev-wcoss2` all reproduced controls using `develop`.

2022-09-26 18:07 UTC, WalterKolczynski-NOAA requested changes

2022-09-26 18:07 UTC, WalterKolczynski-NOAA commented on workflow/hosts/hera.yaml
> +comroot: '/scratch1/NCEPDEV/rstprod/prod/com'
Why is comroot changed on hera?

2022-09-26 18:07 UTC, WalterKolczynski-NOAA commented on util/sorc/webtitle.fd/makefile
> +FC =	ftn
The util directory is being removed by PR #1009. Any changes to these files need to be made as a PR to the [NOAA-EMC/gfs-util](https://github.com/NOAA-EMC/gfs-utils) repo

2022-09-26 18:07 UTC, WalterKolczynski-NOAA commented on jobs/JGDAS_ATMOS_GEMPAK
> +echo "=============== BEGIN TO SOURCE RELEVANT CONFIGS ==============="
The preamble announces the script beginning, it isn't needed here.

2022-09-26 18:07 UTC, WalterKolczynski-NOAA commented on jobs/JGFS_ATMOS_GEMPAK
> +echo "=============== BEGIN GEMPAK ==============="
Same here. The preamble announces the script start.

2022-09-26 18:07 UTC, WalterKolczynski-NOAA commented on jobs/JGLOBAL_ATMOS_NCEPPOST
> +export HOMECRTM=${HOMECRTM:-${PACKAGEROOT:-}/lib/crtm/${crtm_ver:-}}
With empty default values for PACKAGEROOT and crtm_ver here, this line will produce incorrect paths but not error.

2022-09-26 18:07 UTC, WalterKolczynski-NOAA commented on parm/config/config.base.emc.dyn
> +#export HOMEobsproc="$BASE_GIT/obsproc/v1.1.0"
Remove dead code. Why are we not using the v1.1.0?

2022-09-26 18:07 UTC, WalterKolczynski-NOAA commented on parm/config/config.resources.nco.static
> +#!/bin/ksh -x
I know this is copied from ops branch, but we've already converted all the others to bash.

2022-09-27 18:02 UTC, KateFriedman-NOAA commented on workflow/hosts/hera.yaml
> +comroot: '/scratch1/NCEPDEV/rstprod/prod/com'
I have reverted it back to the prior setting. I had changed it to the new prod mirror location (/scratch1/NCEPDEV/rstprod/prod/com) so the tracker could get the syndat files but NCO won't add syndat to the mirror until next year (put in request last week).

Instead, I have:
1. Updated the existing syndat folder under /scratch1/NCEPDEV/global/glopara/com on Hera and /work/noaa/global/glopara/com/gfs/prod/syndat on Orion with the current syndat from ops on WCOSS2.
2. Added `cominsyn` paths to the hosts files.
3. Updated the setup scripts and `config.base.emc.dyn` to set `COMINsyn` using `cominsyn` from the hosts files.

2022-09-27 18:03 UTC, KateFriedman-NOAA commented on parm/config/config.base.emc.dyn
> +#export HOMEobsproc="$BASE_GIT/obsproc/v1.1.0"
I have reverted this back to the prior HOMEobsproc* variables. Need additional updates for the new prepobs modulefile so I will update obsproc/prepobs in a separate PR.

2022-09-27 18:04 UTC, KateFriedman-NOAA commented on parm/config/config.base.emc.dyn
> +#export HOMEobsproc="$BASE_GIT/obsproc/v1.1.0"
Also, obsproc.v1.1.0 is coming with GFSv16.3, we're at v1.0.2 for GFSv16.2. Waiting for final tag of v1.1.0, may update to v1.0.2 in `develop` first. The prepobs version is v1.0.1 in both GFS versions.

2022-09-27 18:06 UTC, KateFriedman-NOAA commented on jobs/JGLOBAL_ATMOS_NCEPPOST
> +export HOMECRTM=${HOMECRTM:-${PACKAGEROOT:-}/lib/crtm/${crtm_ver:-}}
Good catch. Should we fix the empty defaults in this PR or your task to remove "NCEP" from the post script names?

2022-09-27 18:10 UTC, WalterKolczynski-NOAA commented on jobs/JGLOBAL_ATMOS_NCEPPOST
> +export HOMECRTM=${HOMECRTM:-${PACKAGEROOT:-}/lib/crtm/${crtm_ver:-}}
Here. Just throw in some question marks if you need to.

2022-09-27 18:12 UTC, KateFriedman-NOAA commented on jobs/JGDAS_ATMOS_GEMPAK
> +echo "=============== BEGIN TO SOURCE RELEVANT CONFIGS ==============="
I removed lines 8 and 9. Should lines 10 and 11 go as well?

2022-09-27 18:12 UTC, KateFriedman-NOAA commented on jobs/JGFS_ATMOS_GEMPAK
> +echo "=============== BEGIN GEMPAK ==============="
Removed.

2022-09-27 18:12 UTC, KateFriedman-NOAA commented on parm/config/config.resources.nco.static
> +#!/bin/ksh -x
Converted to bash. Thanks for catching!

2022-09-27 18:13 UTC, WalterKolczynski-NOAA commented on jobs/JGDAS_ATMOS_GEMPAK
> +echo "=============== BEGIN TO SOURCE RELEVANT CONFIGS ==============="
Probably, if only because other scripts don't do it.

2022-09-27 18:15 UTC, WalterKolczynski-NOAA commented on parm/config/config.base.emc.dyn
> +#export HOMEobsproc="$BASE_GIT/obsproc/v1.1.0"
Okay, I just saw the nco version of this file using 1.1.0, so I was wondering why the difference.

2022-09-27 18:17 UTC, KateFriedman-NOAA commented on jobs/JGLOBAL_ATMOS_NCEPPOST
> +export HOMECRTM=${HOMECRTM:-${PACKAGEROOT:-}/lib/crtm/${crtm_ver:-}}
Done!

2022-09-27 18:18 UTC, KateFriedman-NOAA commented on parm/config/config.base.emc.dyn
> +#export HOMEobsproc="$BASE_GIT/obsproc/v1.1.0"
That was me getting ahead of things to set the incoming ops version in the nco version of that config. I'll redo the nco config obsproc update when I do the dev side change now instead.

2022-09-27 18:21 UTC, KateFriedman-NOAA commented on jobs/JGDAS_ATMOS_GEMPAK
> +echo "=============== BEGIN TO SOURCE RELEVANT CONFIGS ==============="
Done. I also removed the other "BEGIN TO SOURCE" announcement for the env file.

2022-09-27 18:21 UTC, KateFriedman-NOAA commented on jobs/JGFS_ATMOS_GEMPAK
> +echo "=============== BEGIN GEMPAK ==============="
I also removed the other "BEGIN TO SOURCE" announcement for the env file.

2022-09-27 18:23 UTC, KateFriedman-NOAA commented on util/sorc/webtitle.fd/makefile
> +FC =	ftn
Reverted, Will address in `gfs-util` repo as needed.

2022-09-27 18:27 UTC, KateFriedman-NOAA commented
Sync merged with `develop` and resolved conflict in `workflow/hosts/orion.yaml`.

2022-09-27 18:32 UTC, KateFriedman-NOAA commented
@WalterKolczynski-NOAA I believe I have addressed your comments. Let me know if not or if you have any others. Thanks!

2022-09-29 02:19 UTC, WalterKolczynski-NOAA approved these changes

2022-09-29 15:09 UTC, merged