First step towards making j-jobs consistent in use from ecflow and rocoto
NOAA-EMC/global-workflow pull request #1080
Opened 2022-10-18 02:20 UTC by aerorahul

**Description**

Several jobs run in development mode do not adhere to EE2 standards.  Sometimes these development jobs do get used for operations at which time there is a rush in getting them to be standardized.
These jobs are also used to run parallel retrospectives and near-real time parallels.

This work is performed with GFSv17 and GEFSv13 as the target implementation.

This PR attempts to standardize the use of several variables as defined in the NCO EE2 standards document.
Specifically;
The following are defined in the job-card:
`DATAROOT`
`cyc`
`HOMEgfs`
`job`
`jobid=$job/$$` or `jobid=$PBS_JOBNAME/$PBS_JOBID` depending on Rocoto/Ops

The following are defined in the j-job:
`pid`
`DATA=DATAROOT/jobid`
`cycle`

**Type of change**

- [X] New feature (non-breaking change which adds functionality)

It is not intended to break any frequently used existing features, however testing of several features e.g. WAFS jobs, BUFRSND jobs are untested in `develop`.  It is unlikely these jobs run in `develop` to begin with and fixing them will be done in a future PR.

Several of the development jobs e.g. `vrfy`, `metp`, `prep`, `ocnpost`, `arch`, `earc` do not follow EE2 standards.
Testing was done to ensure these jobs run without failure, however extended testing is necessary to validate these tests as some of these jobs require extended data to be generated.

Future additions of jobs/scripts will be checked for EE2 compliance, regardless of if it is used in development or operations.

**How Has This Been Tested?**
All tests were performed on Orion.
- [X] Cycled test for two and half cycles
- [X] Single prototype S2SW forecast-only test case
  
**Checklist**

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [?] New and existing tests pass with my changes
- [X] Any dependent changes have been merged and published

2022-10-18 02:31 UTC, aerorahul commented on scripts/exgfs_atmos_post.sh
> +          -new_grid ${wafsgrid} "${PGBOUT}.tmp"
This is fixing a linter recommendation that caused the failure.
Mental note to self: Not all linter warnings are accurate.

2022-10-18 16:30 UTC, WalterKolczynski-NOAA requested changes
Only big thing is the j-job header idea we discussed on the call. Maybe we can have a footer too, though I think right now it would just be for deleting `${DATA}`.

2022-10-18 16:30 UTC, WalterKolczynski-NOAA commented on jobs/JGDAS_ATMOS_ANALYSIS_DIAG
> +
As discussed in the call, I think we can move all this to a jjob header script that is sourced to have one for all j-jobs.

2022-10-18 16:30 UTC, WalterKolczynski-NOAA commented on scripts/exgfs_atmos_post.sh
> +          -new_grid ${wafsgrid} "${PGBOUT}.tmp"
Add a `# shellcheck disable=SC2086` before this line and a `shellcheck disable=` after to suppress the warning permanently.

2022-10-18 16:30 UTC, WalterKolczynski-NOAA commented on scripts/exglobal_atmos_analysis.sh
> +RTMFIX=${CRTM_FIX}
If we are going to do this, we should remove the line from `config.base` that sets `${RTMFIX}`, since changing it won't do anything.

2022-10-18 16:30 UTC, WalterKolczynski-NOAA commented on workflow/applications.py
> +        self.do_wafs = _base.get('WAFSF', False)
Is there a todo to change this to `DO_WAFS` wherever it is being used so we can change it back to match the other settings?

2022-11-15 20:04 UTC, aerorahul commented
will reopen from my fork.
closing.

2022-11-15 20:04 UTC, closed without merging