GFS-UTILS update for build and ush scripts
NOAA-EMC/global-workflow pull request #1082
Opened 2022-10-20 19:58 UTC by KateFriedman-NOAA

**Description**

This PR updates the gfs-utils version and ush script symlinks/paths. This will resolve issue #1059 until `finddate.sh` can be used via the `prod_util` module.

* A number of ush scripts were moved into the new gfs-utils repo but not added to `link_workflow.sh`. This PR adds them to `link_workflow.sh`.
* Several workflow scripts are updated to point to the gfs-utils ush symlinks under the top level `/ush` folder instead of the prior `/util/ush` folder.

Awaiting an updated hash from gfs-utils (after `feature/consistent` is merged). Needed as a companion update for this workflow PR. This is also needed for WCOSS2 support.

**Type of change**

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

- [x] Clone and build tests on WCOSS2, Hera, Orion
- [x] Cycled tests on WCOSS2, Hera, Orion
  
Addresses #1059

2022-10-20 20:02 UTC, aerorahul approved these changes
Looks good. Does this PR bring in the new hash of gfs-utils `develop` or are we still pointing to `feature/consistent`?
Also, just a note for TODO, `finddate.sh` is a part of `prod_util`.  In the future we could just use it from there.
Thanks @KateFriedman-NOAA

2022-10-20 20:21 UTC, KateFriedman-NOAA commented
Merged `feature/consistent` into gfs-utils `develop` and updated hash (af933d3) in this PR.

2022-10-20 21:57 UTC, WalterKolczynski-NOAA requested changes

2022-10-20 21:57 UTC, WalterKolczynski-NOAA commented on sorc/build_gfs_utils.sh
> +"${cwd}"/gfs_utils.fd/ush/build.sh
Just quote the whole path.

2022-10-21 14:03 UTC, KateFriedman-NOAA commented on sorc/build_gfs_utils.sh
> +"${cwd}"/gfs_utils.fd/ush/build.sh
Done.

2022-10-22 11:26 UTC, WalterKolczynski-NOAA approved these changes

2022-10-22 11:29 UTC, merged