Introduce FHMAX_ENKF_GFS to extending ensemble forecast capabilities
NOAA-EMC/global-workflow pull request #1122
Opened 2022-11-16 22:14 UTC by XianwuXue-NOAA

**Description**
Introduce FHMAX_ENKF_GFS to extending ensemble forecast capabilities for gfsefmn jobs

**Type of change**

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**
Tested it on WCOSS2

  
**Checklist**

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas

2022-11-16 22:21 UTC, aerorahul requested changes
looks good.
some suggestions to remove superfluous if-blocks.

2022-11-16 22:21 UTC, aerorahul commented on scripts/exgdas_enkf_fcst.sh
> +fi
```suggestion
  if [[ ${CDUMP} == "gfs" ]]; then
      export FHMAX=$FHMAX_ENKF_GFS
  fi
```

2022-11-16 22:21 UTC, aerorahul commented on workflow/rocoto/workflow_tasks.py
> +                    fhmax = epos['FHMAX_ENKF_GFS']
```suggestion
              if self.cdump == "gfs":
                  fhmax = epos['FHMAX_ENKF_GFS']
```

2022-11-16 22:28 UTC, XianwuXue-NOAA commented
@aerorahul Thanks. Delete the if conditions.

2022-11-16 22:34 UTC, aerorahul commented on scripts/exgdas_enkf_fcst.sh
> +   export FHMAXF=$FHMAX_ENKF_GFS
There is a typo here on the LHS.
Also, suggest this:
```suggestion
   export FHMAX=${FHMAX_ENKF_GFS:-${FHMAX_ENKF:-${FHMAX}}}
```

2022-11-17 15:46 UTC, aerorahul approved these changes
looks good.

2022-11-17 15:48 UTC, merged