Hotfix/gempak resources
NOAA-EMC/global-workflow pull request #1214
Opened 2023-01-06 03:44 UTC by WalterKolczynski-NOAA

**Description**
The GFS gempak job was using the GDAS settings instead of switching to the GFS settings for `npe` and `npe_node`.

This is part of a package of PRs that were tested together as part of a j-job refactor.

Fixes: #1213

**Type of change**
- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**
- [x] Cycled test on Orion
- [ ] Cycled test on Hera
- [ ] Cycled test on WCOSS2
  
**Checklist**
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

** Dependencies **
This is part of a package of PRs that were tested together as part of a j-job refactor:
#1212

2023-01-06 03:59 UTC, WalterKolczynski-NOAA commented
Draft while I complete the rest of the PR group and get it tested on other machines.

2023-01-06 17:46 UTC, aerorahul requested changes
some simplifications, perhaps.
There are no `gdas` equivalent since the `gempak` step does not run in the late cycle.

2023-01-06 17:46 UTC, aerorahul commented on env/ORION.env
> +
```suggestion
    npe_gempak=${npe_gempak_${CDUMP}}
    npe_node_gempak=${npe_node_gempak_${CDUMP}}
```

2023-01-06 17:46 UTC, aerorahul commented on env/WCOSS2.env
> +    fi
```suggestion
    npe_gempak=${npe_gempak_${CDUMP}}
    npe_node_gempak=${npe_node_gempak_${CDUMP}}

```

2023-01-06 17:46 UTC, aerorahul commented on env/HERA.env
> +
```suggestion
    npe_gempak=${npe_gempak_${CDUMP}}
    npe_node_gempak=${npe_node_gempak_${CDUMP}}
```

2023-01-06 23:54 UTC, WalterKolczynski-NOAA commented
> some simplifications, perhaps. There are no `gdas` equivalent since the `gempak` step does not run in the late cycle.

Not in development currently (see #1219), but `config.resources` has two sets of resources, and there are GDAS gempak j-job scripts. If you look in the ecf directory, those GDAS j-jobs _are_ being called by ECFlow scripts. Maybe those aren't used either in the ECFlow framework, but I have to believe all these are there for a reason beyond code rot.
```
hfe04 ecf/ > grep JGDAS_ATMOS_GEMPAK -R
scripts/gdas/atmos/gempak/jgdas_atmos_gempak_meta_ncdc.ecf:${HOMEgfs}/jobs/JGDAS_ATMOS_GEMPAK_META_NCDC
scripts/gdas/atmos/gempak/jgdas_atmos_gempak.ecf:${HOMEgfs}/jobs/JGDAS_ATMOS_GEMPAK
```
I'll try to figure out how to look at the ops task mesh, or ask @KateFriedman-NOAA to do it on Monday to confirm these are being used.

I do want to convert ALL resources over to explicitly saying gdas at some point (I've done it for the forecast in the stalled ESMF threading work) so we can use the simpler `_${CDUMP}` formulation, but that would be outside the scope of this PR.

2023-01-09 14:59 UTC, KateFriedman-NOAA commented
> I'll try to figure out how to look at the ops task mesh, or ask @KateFriedman-NOAA to do it on Monday to confirm these are being used.

We have both gdas and gfs gempak jobs in ops. They both run for all four cycles daily. Here are the 00z logs for yesterday to show which jobs run for each dump:
```
emc.global@dlogin04> ll /lfs/h1/ops/prod/output/20230108/*gempak*00*| grep gdas                
-rw-r--r-- 1 ops.prod prod    893891 Jan  8 07:11 /lfs/h1/ops/prod/output/20230108/gdas_atmos_gempak_00.o44053753
-rw-r--r-- 1 ops.prod prod    672225 Jan  8 07:12 /lfs/h1/ops/prod/output/20230108/gdas_atmos_gempak_meta_ncdc_00.o44054727
emc.global@dlogin04:/lfs/h2/emc/global/noscrub/emc.global/FIX> ll /lfs/h1/ops/prod/output/20230108/*gempak*00*| grep gfs
-rw-r--r-- 1 ops.prod prod  59636698 Jan  8 05:14 /lfs/h1/ops/prod/output/20230108/gfs_atmos_gempak_00.o44016228
-rw-r--r-- 1 ops.prod prod  19812771 Jan  8 05:15 /lfs/h1/ops/prod/output/20230108/gfs_atmos_gempak_meta_00.o44016229
-rw-r--r-- 1 ops.prod prod    510753 Jan  8 03:44 /lfs/h1/ops/prod/output/20230108/gfs_atmos_gempak_upapgif_00.o44016231
-rw-r--r-- 1 ops.prod prod    510249 Jan  8 09:43 /lfs/h1/ops/prod/output/20230108/gfs_atmos_gempak_upapgif_06.o44079900
-rw-r--r-- 1 ops.prod prod    962280 Jan  8 04:44 /lfs/h1/ops/prod/output/20230108/gfs_atmos_pgrb2_spec_gempak_00.o44026739
-rw-r--r-- 1 ops.prod prod    960448 Jan  8 22:42 /lfs/h1/ops/prod/output/20230108/gfs_atmos_pgrb2_spec_gempak_18.o44220046
-rw-r--r-- 1 ops.prod prod   1149784 Jan  8 04:16 /lfs/h1/ops/prod/output/20230108/gfs_wave_gempak_00.o44017487
```

Here are the gdas jobs family in the ecf def file:
https://github.com/NOAA-EMC/global-workflow/blob/dev/gfs.v16/ecf/defs/gfs_v16_3.def#L2343:L2348

...and the two ecf scripts:
https://github.com/NOAA-EMC/global-workflow/tree/dev/gfs.v16/ecf/scripts/gdas/atmos/gempak

^ those are the versions currently used in ops GFS.v16.3.5, including resources set in ecf scripts.

2023-01-14 16:33 UTC, aerorahul approved these changes

2023-01-15 00:31 UTC, merged