Add mechanism to detect machine and clean module env.
NOAA-EMC/global-workflow pull request #1381
Opened 2023-03-07 18:20 UTC by aerorahul

**Description**

This PR:
- adds `detect_machine.sh` and `module-setup.sh` from ufs-weather-model with some improvements and modifications

Improvements include ability to detect machines from `compute` nodes.
The appending of `COMPILER` to `MACHINE_ID` is not done in `detect_machine.sh`

This work will be used for CI work as well as in the driver jobs. e.g. `rocoto/job_name.sh` or `ecf/job_name.ecf` in the future.

Use of `modulefiles/module-setup.sh.inc` should be deprecated going forward.  These will be removed in the future.

**Type of change**

- [X] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**
This PR just adds these files, so no testing of workflow is necessary.
The test of the scripts can be done via a simple script:
```bash
#!/bin/bash

set -eu
source ush/detect_machine.sh
echo $MACHINE_ID
source ush/module-setup.sh
module list
```
  
This was tested on Hera and Orion on the front end and compute nodes.

**Checklist**

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

2023-03-07 19:31 UTC, WalterKolczynski-NOAA requested changes

2023-03-07 19:31 UTC, WalterKolczynski-NOAA commented on ush/detect_machine.sh
> +MACHINE_ID=${MACHINE:-${MACHINE_ID}}
Any reason not to do this first and not check the hostname at all?

2023-03-07 19:31 UTC, WalterKolczynski-NOAA commented on ush/detect_machine.sh
> +  dlogin10.dogwood.wcoss2.ncep.noaa.gov)     MACHINE_ID=wcoss2 ;; ### dogwood10
Could this just be
```suggestion
*.wcoss2.ncep.noaa.gov) MACHINE_ID=wcoss2 ;;
```

2023-03-07 19:31 UTC, WalterKolczynski-NOAA commented on ush/detect_machine.sh
> +  gaea1[0-6].ncrc.gov) MACHINE_ID=gaea ;; ### gaea10-16
```suggestion
gaea*) MACHINE_ID=gaea ;;
```

2023-03-07 19:31 UTC, WalterKolczynski-NOAA commented on ush/detect_machine.sh
> +  hfe1[0-2]) MACHINE_ID=hera ;; ### hera10-12
```suggestion
hfe*) MACHINE_ID=hera ;;

2023-03-07 19:31 UTC, WalterKolczynski-NOAA commented on ush/detect_machine.sh
> +  chadmin[1-6].ib0.cheyenne.ucar.edu)  MACHINE_ID=cheyenne ;; ### cheyenne1-6
```suggestion
*.cheyenne.ucar.edu) MACHINE_ID=cheyenne ;;
```

2023-03-07 19:31 UTC, WalterKolczynski-NOAA commented on ush/detect_machine.sh
> +  login[1-4].stampede2.tacc.utexas.edu) MACHINE_ID=stampede ;; ### stampede1-4
```suggestion
*.stampede2.tacc.utexas.edu) MACHINE_ID=stampede ;;
```

2023-03-07 19:31 UTC, WalterKolczynski-NOAA commented on ush/detect_machine.sh
> +  login0[1-2].expanse.sdsc.edu) MACHINE_ID=expanse ;; ### expanse1-2
```suggestion
*.expanse.sdsc.edu) MACHINE_ID=expanse ;;
```

2023-03-07 19:31 UTC, WalterKolczynski-NOAA commented on ush/detect_machine.sh
> +  Orion-login-[1-4].HPC.MsState.Edu) MACHINE_ID=orion ;; ### orion1-4
```suggestion
Orion-*.HPC.MsState.Edu) MACHINE_ID=orion ;;
```

2023-03-07 19:31 UTC, WalterKolczynski-NOAA commented on ush/module-setup.sh
> +if [[ ${MACHINE_ID} = jet* ]] ; then
I think this can be done with a `case` instead of `elif`. Up to you though.

2023-03-07 19:41 UTC, aerorahul commented
Like I said, I copied them from ufs-weather-model and made some minor modifications.
globbing is generally a frowned upon idea as you don't know what you will hit.

I think it is better to have an exact match.

2023-03-07 19:54 UTC, WalterKolczynski-NOAA approved these changes

2023-03-08 12:54 UTC, TerrenceMcGuinness-NOAA approved these changes

2023-03-08 12:54 UTC, TerrenceMcGuinness-NOAA commented on ush/module-setup.sh
> +    export SPACK_ROOT=/discover/nobackup/mapotts1/spack
Do we know when this changes in the NASA NCCS machine being it is now pointing to a person's space?

2023-03-08 14:37 UTC, aerorahul commented on ush/module-setup.sh
> +    export SPACK_ROOT=/discover/nobackup/mapotts1/spack
not sure.

2023-03-08 14:38 UTC, merged