Feature/class exceptions
NOAA-EMC/global-workflow pull request #1392
Opened 2023-03-10 21:16 UTC by HenryWinterbottom-NOAA

**Description**

This PR addresses issue #1391. 

**Type of change**

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

The `exceptions.py` module has been test using the corresponding unit-test `tests/test_exceptions.py`.
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

2023-03-10 21:20 UTC, CoryMartin-NOAA approved these changes

2023-03-10 21:28 UTC, aerorahul approved these changes
looks good.
looking forward to raising a `GWException` when it does not fit to a built in exception.

2023-03-10 21:37 UTC, WalterKolczynski-NOAA requested changes

2023-03-10 21:37 UTC, WalterKolczynski-NOAA commented on ush/python/pygw/src/pygw/exceptions.py
> +class Error(Exception):
I would use a less generic class name here, like WorkflowError (or maybe WorkflowException if there is a desire to distinguish it as an abstract class from the concrete `*Error` classes).

2023-03-10 21:37 UTC, WalterKolczynski-NOAA commented on ush/python/pygw/src/tests/test_exceptions.py
> +class TestErrors(Error):
```suggestion
class TestError(Error):
```

2023-03-11 00:48 UTC, WalterKolczynski-NOAA approved these changes

2023-03-11 01:34 UTC, merged