Feature/prep ocn inc ice ana
NOAA-EMC/global-workflow pull request #1485
Opened 2023-04-19 19:26 UTC by guillaumevernieres

## Description
The work in this PR is only meant to bring us closer to a viable WCDA system. The refactoring of the marine DA to the new standard introduced by @aerorahul and used by @RussTreadon-NOAA and @CoryMartin-NOAA will be addressed after this [Epic](https://github.com/noaa-emc/gdasapp/issues/416) is resolved. 

### Motivation and context
This work adds a separate j-job ```JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT ``` that calls a script that will be in the GDASApp for the time being (PR to come once this is merged) and does the following:
- prepares the `SOCA` increment for `MOM6` IAU
- recursively apply the `SOCA2CICE` change of variable. A mapping from the 2D seaice analysis variable to the CICE6 dynamical and thermodynamic variables.
- merge the `Tref` increment from the `NSST` analysis with the `SOCA` increment   

### Summary of the change
- HPC environment: the new j-job runs a `JEDI` executable twice and one python script. All are serial jobs but the JEDI exec need to be called as an MPI job with 1 pe. 
- `jobs/JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT`, that script point to a ex-script that is not in the GDASApp develop yet.
- addition of the option to merge the Tref NSST increment with the MOM6 increment. This is triggered with the `DO_MERGENSST` switch
- The new j-job dependency was added, with the option to wait for the surface analysis file `sfcanl.nc` if `do_mergensst` is true.

This work is mentioned in the `global-workflow` issue #1480.
- Fixes issue https://github.com/NOAA-EMC/GDASApp/issues/418 

### Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

### How Has This Been Tested?
- This work was extracted from a branch that includes all the necessary changes to cycle a WCDA system. It was tested at c48o500 and c384o025.
- It will require a few PR's in the GDASApp to allow others to reproduce our results.
- Only tested on Hera
  
**Checklist**

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

2023-04-19 19:44 UTC, aerorahul approved these changes
looks ok to me.

2023-04-19 19:49 UTC, CoryMartin-NOAA approved these changes

2023-04-21 07:23 UTC, WalterKolczynski-NOAA requested changes
Just some shellcheck solutions. Want to get this in before the COM refactor breaks UFSDA.

2023-04-21 07:23 UTC, WalterKolczynski-NOAA commented on jobs/JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT
> +WIPE_DATA="NO"
Just export it to shut shellcheck up.

2023-04-21 07:23 UTC, WalterKolczynski-NOAA commented on jobs/JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT
> +export GDATE=$(date +%Y%m%d%H -d "${CDATE:0:8} ${CDATE:8:2} - ${assim_freq} hours")
```suggestion
# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153
GDATE=$(date +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
export GDATE
```

2023-04-21 07:23 UTC, WalterKolczynski-NOAA commented on jobs/JGDAS_GLOBAL_OCEAN_ANALYSIS_CHKPT
> +export APREFIX="${CDUMP}.t${cyc}z."
```suggestion
# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153
export APREFIX="${CDUMP}.t${cyc}z."
```

2023-04-21 15:45 UTC, WalterKolczynski-NOAA approved these changes

2023-04-21 15:52 UTC, WalterKolczynski-NOAA commented
@guillaumevernieres I took ashot as changing the PR title on my own but you seem to have reverted it back. Would you please give it a new title that is (a) shorter and (b) uses imperative mood (starts with a verb; it should complete the sentence "This PR will _______").

After that is done, I will merge.

2023-04-21 16:13 UTC, guillaumevernieres commented
You're going to block a merge because you don't like the title of my PR @WalterKolczynski-NOAA ? I will revert to your title if that's what it takes, but do you have a valid reason for editing other people's PR title?

2023-04-21 16:38 UTC, guillaumevernieres commented
Thanks all for your reviews. And whatever for the title ...

2023-04-21 16:40 UTC, merged

2023-04-21 16:40 UTC, WalterKolczynski-NOAA commented
Thanks @guillaumevernieres