Proposed bugfix for warm ICSDIR
NOAA-EMC/global-workflow pull request #1529
Opened 2023-04-26 00:15 UTC by guillaumevernieres

**Description**

- fixes #1528 

Note: I have not tested the flat structure `ICSDIR` 

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**
cycled test with the coupled UFS (S2S).
  
**Checklist**

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

2023-04-26 00:47 UTC, WalterKolczynski-NOAA requested changes
Thanks. Fix looks correct. Would you mind also taking out the extra 'chem' on L191-192? If not, Otherwise I'll just get it after.

2023-04-26 01:17 UTC, guillaumevernieres commented
> Thanks. Fix looks correct. Would you mind also taking out the extra 'chem' on L191-192? If not, Otherwise I'll just get it after.

Good catch, I cherry picked from an other branch and forgot `chem` ...

2023-04-26 04:16 UTC, WalterKolczynski-NOAA approved these changes

2023-04-26 04:17 UTC, merged

2023-04-26 04:18 UTC, WalterKolczynski-NOAA commented
Thanks @guillaumevernieres for fixing my sloppy mistake.

2023-07-31 17:03 UTC, CoryMartin-NOAA commented on workflow/setup_expt.py
> +    if os.path.isdir(os.path.join(inputs.icsdir, f'{inputs.cdump}.{rdatestr[:8]}', rdatestr[8:], 'model_data', 'atmos')):
I think this was supposed to be `idatestr` not `rdatestr`. If you create cold start ICs from ufs_utils, there won't be a rdate directory.