Avoid parsing group name when checking RadMon diagnostic files
NOAA-EMC/global-workflow pull request #1559
Opened 2023-05-02 13:23 UTC by DavidHuber-NOAA

**Description**

This changes the way the RadMon diagnostic file checker determines if a diagnostic file is 0-sized.  Instead of attempting to parse the output of `tar -tv`, the script now extracts the `radstat` file and runs `du -b` on each gzipped diagnostic file.  On S4, the primary group is `domain users`, which containing a space, caused issues with the previous method.

Fixes #1515

**Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

- [x] Cycled test on S4
- [x] Cycled test on Orion
- [x] Cycled test on Hera
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes

2023-05-02 14:33 UTC, EdwardSafford-NOAA approved these changes
Looks good to me.

2023-05-02 22:17 UTC, WalterKolczynski-NOAA requested changes
Try this alternative way that does not require adding a full untar just for S4 and also eliminates the need for gawk.

2023-05-02 22:17 UTC, WalterKolczynski-NOAA commented on ush/radmon_diag_ck.sh
> -   verbose_contents=`tar -tvf ${radstat_file} | grep '_ges'`
```suggestion
# File sizes contain only digits and immediately precede the date
sizes=($(tar -vtf gdas.t00z.radstat --wildcards '*_ges*' | grep -P -o '(\d)+(?= \d{4}-\d{2}-\d{2})'))
# Filenames are the last group of non-whitespace characters
filenames=($(tar -vtf gdas.t00z.radstat --wildcards '*_ges*' | grep -P -o '\S+$'))
```

2023-05-02 22:17 UTC, WalterKolczynski-NOAA commented on ush/radmon_diag_ck.sh
> +      rm -f "${gz_ges}"
```suggestion
   for file_num in ${!file_names[@]}; do
      file_name="${filenames[${file_num}]}"
      file_size="${sizes[${file_num}]
      
      if (( file_size <= 1000 )); then
        tar -xf ${radstat_file} ${file_name}
        gunzip ${file_name}
        uz_file_name="${file_name%.*}"
        uz_file_size=$(stat -c "%s" "${uz_file_name}")
        
        if (( uz_file_size <= 0 )); then
           # Remove leading diag_
           sat=${uz_file_name#diag_}
           # Remove trailing _ges*
           sat=${sat%_ges*}
           
           zero_len_diag="${zero_len_diag} ${sat}"
        fi
        
        rm -f ${uz_file_name}
```

2023-05-05 16:50 UTC, DavidHuber-NOAA commented on ush/radmon_diag_ck.sh
> -   verbose_contents=`tar -tvf ${radstat_file} | grep '_ges'`
@WalterKolczynski-NOAA these changes work perfectly with just some minor modifications.  However, these two lines result in `shellcheck SC2207` warnings:

`sizes=($(tar -vtf gdas.t00z.radstat --wildcards '*_ges*' | grep -P -o '(\d)+(?= \d{4}-\d{2}-\d{2})'))`
`filenames=($(tar -vtf gdas.t00z.radstat --wildcards '*_ges*' | grep -P -o '\S+$'))`

The suggested fix is in the form

```
array=()
mycommand | while IFS="" read -r line; do array+=("$line"); done
```

but I cannot seem to make this work.  In every case, I am getting empty `sizes` and `filenames` arrays.  Do you have a suggestion on how to make this work or should I add `# shellcheck disable=SC2207 ... # shellcheck disable=` before/after these lines or do you have a suggestion on how to get shellcheck's suggestion to work?

2023-05-08 21:37 UTC, WalterKolczynski-NOAA commented on ush/radmon_diag_ck.sh
> -   verbose_contents=`tar -tvf ${radstat_file} | grep '_ges'`
Try the other suggested form:
```
IFS=" " read -r -a array <<< "$(mycommand)"
```

If that doesn't work, add a shellcheck disable directive along with a TODO to look into it later (as opposed to others we have that are permanent).

2023-05-09 15:15 UTC, DavidHuber-NOAA commented on ush/radmon_diag_ck.sh
> -   verbose_contents=`tar -tvf ${radstat_file} | grep '_ges'`
@WalterKolczynski-NOAA Unfortunately, that didn't work either.  I will go ahead with the original solution and add the TODO and shellcheck disable directive.  For reference, these are the options I tried:

```
   sizes=()
   tar -vtf ${radstat_file} --wildcards '*_ges*' | \
      grep -P -o '(\d)+(?= \d{4}-\d{2}-\d{2})' | \
      while IFS="" read -r size; do sizes+=("$size"); done
```
and
```
   sizes=()
   IFS=" " read -r -a sizes <<< "$(tar -vtf ${radstat_file} --wildcards '*_ges*' | \
      grep -P -o '(\d)+(?= \d{4}-\d{2}-\d{2})')"
```

The first returned an empty array and the second contained only one element even though the tarball contains ~15 files.

2023-05-10 02:35 UTC, WalterKolczynski-NOAA approved these changes

2023-05-10 02:36 UTC, merged

2023-05-10 02:36 UTC, WalterKolczynski-NOAA commented
@DavidHuber-NOAA Thanks for making the change.