Remove WAFS references from global-workflow
NOAA-EMC/global-workflow pull request #1642
Opened 2023-05-22 21:40 UTC by aerorahul

**Description**
This PR removes WAFS references, etc. from the global-workflow following the approval from NCEP director on making WAFS a standalone post-processing package.

Fixes #1641 

**Type of change**

- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

**How Has This Been Tested?**
- Setup scripts should work and provide no `WAFS` dependencies or scripts in the workflow
- offline UPP scripts should work for analysis as they were updated to remove WAFS references.
 
**Checklist**

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] New and existing tests pass with my changes
- [X] Any dependent changes have been merged and published

2023-05-22 21:49 UTC, WalterKolczynski-NOAA approved these changes

2023-05-23 13:45 UTC, KateFriedman-NOAA approved these changes

2023-05-23 16:17 UTC, WalterKolczynski-NOAA requested changes, later dismissed

2023-05-23 16:17 UTC, WalterKolczynski-NOAA commented on ecf/setup_ecf_links.sh
> +cd "${ECF_DIR}"/scripts/gdas/atmos/post
Use canonical quotes please.

2023-05-23 16:29 UTC, WalterKolczynski-NOAA approved these changes

2023-05-23 23:44 UTC, merged