develop README.md Badges depending on CI Labels
NOAA-EMC/global-workflow pull request #1685
Opened 2023-06-09 16:44 UTC by TerrenceMcGuinness-NOAA

**Description**

As a global-workflow developer, I need to see the status of the current state of the CI builds and runs as GitHub badges in its **README.md**  display so I can easily see the state and stability of the develop branch.

**Requirements**
 
Use GitHub's Workflow Actions so we can generate the badges in the README.md file for the development branch.
The GitHub Actions will update the badges only when a PR is merged to the **develop** branch and only update them occording to the state of the Labels in the PR itself.

This Action must be able to use the final state of the CI labels of the PR so must be able to dynamically "pull" then from the PR just before said merge.

Here will be the map between the Label states and the Badges (for Orion and Hera respectively):

```
Pass -> Pass
Fail -> Fail
None -> Pending
```

For example, if the Badges are currently _Pass_ and a PR is merged without CI test Pass Label the corresponding Badge will be updated to _Pending_.

**Acceptance Criteria (Definition of Done)**

The badges work and correctly display the state of the develop branch in the **README.md** file that reflects the CI Labels of the PR just before it is merged.

- [x] Merged with test develop branch and Badges are displayed in test develop branch from the test merge
- [ ] Cycled test on Orion
- [ ] Forecast-only test on Hera
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

2023-06-09 17:41 UTC, aerorahul approved these changes
looks good.

2023-06-12 16:02 UTC, WalterKolczynski-NOAA requested changes
Seems like there is no way to clear a pending status beyond merging another PR. A future PR should trigger CI testing on "workflow_dispatch" that will update the labels when complete.

2023-06-12 16:02 UTC, WalterKolczynski-NOAA commented on .github/workflows/hera.yaml
> +    if: contains( needs.getlabels.outputs.labels, 'CI-Hera-Passed') && github.event.pull_request.merged
Shouldn't the entire job just be enclosed within a `if: github.event.pull_request.merged`? There's no need to run any of it if the PR wasn't merged.

2023-06-12 16:02 UTC, WalterKolczynski-NOAA commented on .github/workflows/hera.yaml
> +      - name: Get Lables Steps
```suggestion
      - name: Get Label Steps
```

2023-06-12 16:02 UTC, WalterKolczynski-NOAA commented on .github/workflows/orion.yaml
This is nearly identical to the Hera one. Can't we just have a single action that loops over the machines?

2023-06-12 19:34 UTC, TerrenceMcGuinness-NOAA commented on .github/workflows/hera.yaml
> +    if: contains( needs.getlabels.outputs.labels, 'CI-Hera-Passed') && github.event.pull_request.merged
Yes (sort of) the `if:` syntax is inside each job, but yes, after I pondered your question I found we could do this (see below) making the && for merging redundant.

```
on
  pull_request_review:
    types:
      - submitted
```

I'll have to test it though of course.

2023-06-12 19:37 UTC, TerrenceMcGuinness-NOAA commented on .github/workflows/hera.yaml
> +    if: contains( needs.getlabels.outputs.labels, 'CI-Hera-Passed') && github.event.pull_request.merged
Oh, point of order, passed: is a job.  The file has 4 jobs: one for getting the Labels dynamically, and the other three for getting the state of the badge for each case.

2023-06-12 22:15 UTC, TerrenceMcGuinness-NOAA reviewed
bunch of comments with answers

2023-06-12 22:15 UTC, TerrenceMcGuinness-NOAA commented on .github/workflows/hera.yaml
> +    if: contains( needs.getlabels.outputs.labels, 'CI-Hera-Passed') && github.event.pull_request.merged
Oh but darn, I'm not sure there is a `pull_request_review_target` and we need the `target` for this to work on forked PRs.

2023-06-12 22:15 UTC, TerrenceMcGuinness-NOAA commented on .github/workflows/hera.yaml
> +    if: contains( needs.getlabels.outputs.labels, 'CI-Hera-Passed') && github.event.pull_request.merged
Ok, took a deeper dive, here is a GitHub discussion that came to the same conclusion in my original logic that have with this: ([discussion](https://github.com/orgs/community/discussions/26724)).

2023-06-12 22:15 UTC, TerrenceMcGuinness-NOAA commented on .github/workflows/orion.yaml
Note that I can see - not sure how we could "loop" over the `with:` structure value pairs with variables.  These are YAML files BTW not code albeit the run section has code in it.

2023-06-12 23:34 UTC, WalterKolczynski-NOAA commented on .github/workflows/orion.yaml
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs

2023-06-13 13:43 UTC, TerrenceMcGuinness-NOAA reviewed
suggestions are nice but not actionable

2023-06-13 16:17 UTC, TerrenceMcGuinness-NOAA commented on .github/workflows/orion.yaml
Oh there it is!  Yes, I had saw "matrix" and had been glossing over it.  Looks like correct solution.  See that's why we have reviews!!

2023-06-13 19:20 UTC, WalterKolczynski-NOAA commented on .github/workflows/orion.yaml
Deferred to a future PR.

2023-06-13 19:53 UTC, WalterKolczynski-NOAA approved these changes

2023-06-13 19:56 UTC, merged