Update snow DA cycling for the fractional grid setting.
NOAA-EMC/global-workflow pull request #1687
Opened 2023-06-11 15:16 UTC by jiaruidong2017

This PR will allow users to run JEDI-based LETKFOI update for snow depth analysis w/o the fractional grids settings of GFSv17. 

In previous GFS versions, the variable for total snow depth (`snwdph`) was only defined over land grid cells. In the new GFSv17 restarts, with fractional grids, the `snwdph` variable in the restarts is the average snow depth over the grid cell [ = area-weighted average of the snow depth over sea ice (`snodi`) and over land (`snodl`)]. `snodl` is the snow depth over land portion of a cell, `snodi` is the snow depth over ice portion of a cell, and `snwdph` is the snow depth over the entire grid cell. 

This PR depend on:
https://github.com/NOAA-EMC/GDASApp/pull/504

**Type of change**

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

Ran a standalone landanl.sh job on Hera.
  
**Checklist**

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] Any dependent changes have been merged and published

2023-06-12 15:58 UTC, aerorahul requested changes
Please see inline comments.

2023-06-12 15:58 UTC, aerorahul commented on sorc/link_workflow.sh
> +    ${LINK} "${script_dir}/gdas.cd/ush/land/gfs-land_gfsv17.yaml"          .
Why is a yaml file being linked into `ush`?

2023-06-12 15:58 UTC, aerorahul commented on parm/parm_gdas/land_jedi_fix_gfsv17.yaml
> +- [$(HOMEgfs)/ush/gfs-land_gfsv17.yaml, $(DATA)/fv3jedi/gfs-land.yaml]
Why is this in `ush`?  This should be a file in `$(HOMEgfs)/parm/parm_gdas/...`

2023-06-12 15:58 UTC, aerorahul commented on ush/python/pygfs/task/land_analysis.py
> +            jedi_fix_list_path = os.path.join(self.task_config.HOMEgfs, 'parm', 'parm_gdas', 'land_jedi_fix.yaml')
I think we can do this in the `land_jedi_fix.yaml` itself instead of in the python script.

2023-06-12 15:58 UTC, aerorahul commented on parm/parm_gdas/land_jedi_fix_gfsv17.yaml
> +- [$(HOMEgfs)/ush/gfs-land_gfsv17.yaml, $(DATA)/fv3jedi/gfs-land.yaml]
I think we can handle this case in the `land_jedi_fix.yaml`  itself instead of adding this yaml.

2023-06-12 15:58 UTC, aerorahul commented on .gitignore
> +ush/gfs-land_gfsv17.yaml
why is a yaml in a `ush`?

2023-06-12 17:49 UTC, jiaruidong2017 commented
Thanks @aerorahul for your quick review. I did agree with all you suggestions. 

However, we just had a meeting and plan to handle the fractional grid issue in JEDI fv3-jedi repo directly. Therefore, I will close this PR. Thanks again.

2023-06-12 18:18 UTC, jiaruidong2017 commented
@aerorahul @CoryMartin-NOAA I have a concern. The current global-workflow supports both fractional grid cells and non fractional grid cells. If the above proposed changes are made in the JEDI fv3-jedi repo, the snow DA cycling will not work any more for the non fractional grid settings.

2023-06-26 18:18 UTC, aerorahul commented
> @aerorahul @CoryMartin-NOAA I have a concern. The current global-workflow supports both fractional grid cells and non fractional grid cells. If the above proposed changes are made in the JEDI fv3-jedi repo, the snow DA cycling will not work any more for the non fractional grid settings.

@jiaruidong2017 
global-workflow does not support non-fractional grid IIRC.  v17 will use fractional grid to my knowledge.

2023-07-06 14:35 UTC, CoryMartin-NOAA commented
So is this PR able to be closed then?

2023-07-06 16:55 UTC, jiaruidong2017 commented
As I mentioned in GDASApp's PR, the proposed changes can support both fractional and non fractional grids in the global-workflow.

2023-07-06 17:01 UTC, CoryMartin-NOAA commented
@jiaruidong2017 is that true for the model or just the DA?

2023-07-06 17:02 UTC, aerorahul commented
The workflow no longer supports non-fractional grid.

2023-07-06 17:07 UTC, jiaruidong2017 commented
@CoryMartin-NOAA I mean for snow DA only

2023-07-06 17:08 UTC, CoryMartin-NOAA commented
@jiaruidong2017 if the model doesn't support it, then there is no real need for us to support both for the snow DA

2023-07-06 17:08 UTC, jiaruidong2017 commented
@aerorahul Do you mean we need to remove all `FRAC_GRID`?

2023-07-06 17:10 UTC, JessicaMeixner-NOAA commented
The ufs-weather-model itself does support both fractional and non-fractional grid to my knowledge.  @junwang-noaa can correct if needed.

2023-07-06 17:12 UTC, jiaruidong2017 commented
@CoryMartin-NOAA I have no idea whether the model support the non fractional grid or not, and I will check this with @barlage

2023-07-06 17:13 UTC, jiaruidong2017 commented
Thanks @JessicaMeixner-NOAA for your info.

2023-07-06 17:17 UTC, CoryMartin-NOAA reviewed
FRAC_GRID is still a variable in the workflow from a search, so from what I can tell, this one line change looks good to me. But is this PR in draft waiting for a GDASApp hash?

2023-07-06 17:19 UTC, jiaruidong2017 commented
@CoryMartin-NOAA Yes, this PR depends on the GDASApp PR #504

2023-07-06 17:27 UTC, junwang-noaa commented
Yes, the model does support both fractional grid and non-fractional grid.

2023-07-06 17:27 UTC, aerorahul commented
The model does support non-fractional grids.
GFSv17 and GEFSv13 are only implementing fractional grids.
The global-workflow has a variable `FRAC_GRID`, however, the workflow does not support non-fractional grid configurations.  We may remove `FRAC_GRID` references from the global-workflow.
Use at your own risk.

2023-07-10 18:11 UTC, jiaruidong2017 commented
The `gfs-land.yaml` in the fix `fv3jedi` directory need to be updated for the snow DA cycling in the global-workflow. 
@WalterKolczynski-NOAA Would you please copy the file below:  
`/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.9/fv3-jedi/test/Data/fieldmetadata/gfs-land.yaml`
to: 
`${FIX_DIR}/gdas/fv3jedi/20220805/fieldmetadata/gfs-land.yaml`

`FIX_DIR` can be found in `sorc/link_workflow.sh` for different platforms as below: 
```
  "wcoss2")   FIX_DIR="/lfs/h2/emc/global/noscrub/emc.global/FIX/fix" ;;
  "hera")     FIX_DIR="/scratch1/NCEPDEV/global/glopara/fix" ;;
  "orion")    FIX_DIR="/work/noaa/global/glopara/fix" ;;
  "jet")      FIX_DIR="/lfs4/HFIP/hfv3gfs/glopara/git/fv3gfs/fix" ;;
  "s4")       FIX_DIR="/data/prod/glopara/fix" ;;
```

Since there are many changes in `fieldmetadata` and `fv3files`, you may want to update the `fv3jedi` link to a new date `yyyymmdd` by copy the following directories: 
```
/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.9/fv3-jedi/test/Data/fieldmetadata
/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.9/fv3-jedi/test/Data/fv3files
```
to: 
`${FIX_DIR}/gdas/fv3jedi/yyyymmdd/`

Please let me and @CoryMartin-NOAA know if you have any questions. Thanks.

2023-07-10 18:31 UTC, aerorahul commented
> The `gfs-land.yaml` in the fix `fv3jedi` directory need to be updated for the snow DA cycling in the global-workflow. @WalterKolczynski-NOAA Would you please copy the file below: `/scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.9/fv3-jedi/test/Data/fieldmetadata/gfs-land.yaml` to replace: `${FIX_DIR}/gdas/fv3jedi/20220805/fieldmetadata/gfs-land.yaml`
> 
> `FIX_DIR` can be found in `sorc/link_workflow.sh` for different platforms as below:
> 
> ```
>   "wcoss2")   FIX_DIR="/lfs/h2/emc/global/noscrub/emc.global/FIX/fix" ;;
>   "hera")     FIX_DIR="/scratch1/NCEPDEV/global/glopara/fix" ;;
>   "orion")    FIX_DIR="/work/noaa/global/glopara/fix" ;;
>   "jet")      FIX_DIR="/lfs4/HFIP/hfv3gfs/glopara/git/fv3gfs/fix" ;;
>   "s4")       FIX_DIR="/data/prod/glopara/fix" ;;
> ```
> 
> Since there are many changes in `fieldmetadata` and `fv3files`, you may want to update the `fv3jedi` link to a new date `yyyymmdd` by copy the following directories:
> 
> ```
> /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.9/fv3-jedi/test/Data/fieldmetadata
> /scratch2/NCEPDEV/stmp1/Jiarui.Dong/gdasapp/gdasapp.9/fv3-jedi/test/Data/fv3files
> ```
> 
> to: `${FIX_DIR}/gdas/fv3jedi/yyyymmdd/`
> 
> Please let me and @CoryMartin-NOAA know if you have any questions. Thanks.

@jiaruidong2017 
There is a separate template for updating fix files.
Please open an issue using that template and provide the details for the update.

2023-07-10 18:35 UTC, aerorahul requested changes
@jiaruidong2017 
There are references to `FRAC_GRID` in `land_analysis.py`.  Please remove them.
Also, https://github.com/NOAA-EMC/GDASApp/blob/develop/parm/land/letkfoi/apply_incr_nml.j2 still contains a variable `FRAC_GRID`. It should be replaced to be `.true.`

2023-07-10 19:42 UTC, aerorahul approved these changes
Thanks for making the change @jiaruidong2017 
Should we wait for the NOAA-EMC/GDASApp#527 to be merged before merging this PR?

2023-07-10 20:01 UTC, jiaruidong2017 commented
> Thanks for making the change @jiaruidong2017 Should we wait for the [NOAA-EMC/GDASApp#527](https://github.com/NOAA-EMC/GDASApp/pull/527) to be merged before merging this PR?

I believe it depends on GDASApp#527, and we should wait for it. Thank you.

2023-07-11 00:08 UTC, jiaruidong2017 commented
This PR depends on the `merge develop to feature/stable-nightly` in GDASApp, and I will update the commit hash.

2023-07-11 14:53 UTC, jiaruidong2017 commented
@CoryMartin-NOAA The simple changes below in `link_workflow.sh` can solve my issues. 

```
<   for gdas_sub in crtm fv3jedi gsibec; do
---
>   for gdas_sub in crtm gsibec; do
176a177,180
>   if [[ -d "fv3jedi" ]]; then
>      rm -rf "fv3jedi"
>   fi
>   ${LINK_OR_COPY} "${script_dir}/gdas.cd/fv3-jedi/test/Data" "fv3jedi"
```
This change just links the `fv3jedi` to the `fv3-jedi` through GDASApp. How do you think? Thanks.

2023-07-13 06:29 UTC, WalterKolczynski-NOAA approved these changes
Provisionally approved pending CI tests.

2023-07-13 12:58 UTC, CoryMartin-NOAA approved these changes

2023-07-13 13:43 UTC, jiaruidong2017 commented
@CoryMartin-NOAA Would you please merge `develop` into `feature/stable-nightly` in GDASApp so that I could update the commit hash  to include my recent changes? Thanks.

2023-07-13 13:45 UTC, aerorahul requested changes
Apologies, but the `GDASApp` hash needs to be updated in `Externals.cfg` as well.

2023-07-13 13:45 UTC, aerorahul commented on sorc/checkout.sh
> +  checkout "gdas.cd" "https://github.com/NOAA-EMC/GDASApp.git" "e61e33c"; errs=$((errs + $?))
Sorry, I didn't catch this, but this hash needs to be also updated in `Externals.cfg`

2023-07-13 13:45 UTC, CoryMartin-NOAA commented
@jiaruidong2017 I cannot do that as that would break other capabilities as develop does not currently build for GDASApp due to a CRTM issue.

2023-07-14 12:36 UTC, CoryMartin-NOAA commented
@jiaruidong2017 verify that https://github.com/NOAA-EMC/GDASApp/commit/4452b0afb088c240e34fa73af756a91cfe045491 has what you need and if so, update this PR to use this commit

2023-07-14 12:58 UTC, jiaruidong2017 commented
Thanks @CoryMartin-NOAA and I will test the https://github.com/NOAA-EMC/GDASApp/commit/4452b0afb088c240e34fa73af756a91cfe045491

2023-07-14 14:30 UTC, jiaruidong2017 commented on sorc/checkout.sh
> +  checkout "gdas.cd" "https://github.com/NOAA-EMC/GDASApp.git" "e61e33c"; errs=$((errs + $?))
This has been updated. Thanks.

2023-07-14 14:31 UTC, CoryMartin-NOAA approved these changes

2023-07-19 20:58 UTC, WalterKolczynski-NOAA commented
Is this ready to merge?

2023-07-20 15:58 UTC, aerorahul approved these changes
looks good.

2023-07-20 15:59 UTC, aerorahul commented
Assuming the hashes of `gdasapp` are correct, merging now.

2023-07-20 16:00 UTC, merged