Create gw_setup script and extend to other machines
NOAA-EMC/global-workflow pull request #1706
Opened 2023-06-22 19:57 UTC by WalterKolczynski-NOAA

**Description**

In an effort to make workflow setup easier for users, a new script is added to handle setting up the lmod environment needed to run all the setup for checkout and experiment generation. Corresponding modules had already been created for hera and orion for CI testing; these have now been extended to cover other supported machines.

`checkout.sh` now uses this script as more recent versions of `git` are needed on some machines. (Build scripts already load their own modules, so nothing new is needed there.)

Documentation has been updated to recommend this method on all machines rather than the previous instructions.

Closes #1677

**Type of change**

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

**How Has This Been Tested?**

- [ ] Clone, build, and expt setup on orion
- [ ] Clone, build, and expt setup on hera
- [ ] Clone, build, and expt setup on wcoss2
- [ ] Clone, build, and expt setup on jet
- [ ] Clone, build, and expt setup on s4
  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes need updates to the documentation. I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes

2023-06-22 19:58 UTC, WalterKolczynski-NOAA commented
@DavidHuber-NOAA I have no way of testing this on S4. Can you test and make any necessary modifications?

2023-06-22 19:59 UTC, WalterKolczynski-NOAA commented
Personal testing pending before launching CI.

2023-06-22 20:00 UTC, WalterKolczynski-NOAA commented
Updated documentation build: https://global-workflow--1706.org.readthedocs.build/en/1706/

2023-06-22 20:03 UTC, aerorahul approved these changes
looks good.

2023-06-26 11:30 UTC, DavidHuber-NOAA requested changes
This works well on S4 after adding two additional module loads.  Thanks for developing this!

2023-06-26 11:30 UTC, DavidHuber-NOAA commented on modulefiles/module_gwsetup.s4.lua
> +load(pathJoin("miniconda", "3.8-s4"))
Two additions required by S4:

```
load(pathJoin("rocoto","1.3.5"))
load(pathJoin("git","2.30.0"))
```

2023-06-26 18:15 UTC, aerorahul commented on modulefiles/module_gwsetup.s4.lua
> +load(pathJoin("miniconda", "3.8-s4"))
```suggestion
load(pathJoin("miniconda", "3.8-s4"))
load(pathJoin("rocoto","1.3.5"))
load(pathJoin("git","2.30.0"))
```

2023-06-26 18:16 UTC, aerorahul approved these changes

2023-06-26 18:20 UTC, merged