Feature/ccpp
NOAA-EMC/global-workflow pull request #186
Opened 2020-11-12 19:29 UTC by lgannoaa

2020-11-12 19:41 UTC, KateFriedman-NOAA requested changes
Again...there are issues that were not resolved. Please sync your feature/ccpp branch with develop...there are recent changes committed to develop that are getting wiped out in this PR incorrectly. There are also questions I left in PR #184 that didn't get an answer.

PLEASE DO NOT CLOSE THIS PR! Please make fixes in your feature/ccpp branch in your fork, they will automatically show up in this PR when committed to your branch. Closing the PR and restarting it is unnecessary with GitHub. We want the log of questions/comments/changes.

2020-11-12 19:41 UTC, KateFriedman-NOAA commented on parm/config/config.base.emc.dyn
> -export COMROOT="@COMROOT@"
This should not be deleted.

2020-11-12 19:41 UTC, KateFriedman-NOAA commented on parm/config/config.base.emc.dyn
> +export FDATE=$($NDATE +$assim_freq $SDATE)
This should not be added...this is from an old commit. This is not in develop.

2020-11-12 19:41 UTC, KateFriedman-NOAA commented on parm/config/config.base.emc.dyn
> -export FDATE=@FDATE@
This should not be getting deleted.

2020-11-12 19:41 UTC, KateFriedman-NOAA commented on parm/config/config.base.emc.dyn
> -if [[ "$SDATE" = "$CDATE" && $EXP_WARM_START = ".false." ]] || [[ "$DOIAU" = "NO" ]] ; then # Cold starting or IAU off
This line should not be changing. Again, please sync with develop.

2020-11-12 19:41 UTC, KateFriedman-NOAA commented on parm/config/config.base.emc.dyn
> +export DO_METP="YES"                  # Run MET+ jobs
This section should not be changing.

2020-11-12 19:41 UTC, KateFriedman-NOAA commented on parm/config/config.gldas
> -
Remove this extra line.

2020-11-12 19:41 UTC, KateFriedman-NOAA commented on parm/config/config.resources
> +      export nth_anal=10
None of these changes should be happening...please sync with develop!

2020-11-12 20:25 UTC, lgannoaa commented
I tested this package on DELL with C768 as requested by Fanglin by using imp_physics=11.
Fanglin also requested to merge it this package to the develop without testing the imp_physics=8.
Arun told us this merge does not need to reproduce GFSv16 (current develop).

Can you help to test this on other platform as needed? 
User does not need a switch to build the unified forecast executable. It is build with FV3_GSD_v0,FV3_GSD_noah,FV3_GFS_v16beta.

The additional module is not needed. 
I modified this package by:
rm /gpfs/dell2/emc/modeling/noscrub/Lin.Gan/ecflow-dell/feature_ccpp/modulefiles/module_base.wcoss_dell_p3_fcst
rm /gpfs/dell2/emc/modeling/noscrub/Lin.Gan/ecflow-dell/feature_ccpp/ush/load_fv3gfs_modules_fcst.sh
Modify jobs/rocoto/fcst.sh to NOT use the additional module.

The file config.aeroic is not needed for this commit:
rm ush/rocoto/setup_workflow_fcstonly_aeroic.py parm/config/config.aeroic jobs/rocoto/aeroic.sh

config.base.emc.dyn changes need because there are three suites in this configuration. The FV3_GFS_v16beta is one of them. Re-sync with develop.

Comment line in config.resources removed. Re-sync with develop.

build_fv3.sh cleanup is done.

Comment line in checkout.sh removed.

Remove extra line in link_fv3gfs.sh.

2020-11-14 01:14 UTC, WalterKolczynski-NOAA commented
@KateFriedman-NOAA requested this PR not be closed, so I am going to reopen it pending a note of approval from her on this PR that it can be closed without being merged.

2020-11-17 18:29 UTC, KateFriedman-NOAA approved these changes
Initial round of CCPP changes look good. Tests were run on Orion, Hera, and WCOSS-Dell. Caveat: can't run CCPP with waves on yet, further commit will remedy this.

2020-11-17 18:31 UTC, KateFriedman-NOAA commented
This PR will close issue #187 .

2020-11-17 19:01 UTC, merged