Add ocean analysis files to HPSS archiving task
NOAA-EMC/global-workflow pull request #1985
Opened 2023-10-26 15:44 UTC by AndrewEichmann-NOAA

# Description

This PR adds the files under `analysis/ocean` (except those in `bump`) to the HPSS archiving job, in `gdasocean_analysis.tar`, which were previously not archived.

Resolves https://github.com/NOAA-EMC/GDASApp/issues/693

# Type of change

- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?

Tested with WCDA cycling on Hera

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

2023-10-26 15:45 UTC, AndrewEichmann-NOAA commented
FYI @guillaumevernieres

2023-10-26 20:44 UTC, WalterKolczynski-NOAA requested changes

2023-10-26 20:44 UTC, WalterKolczynski-NOAA commented on scripts/exglobal_archive.sh
> +            targrp_list="${targrp_list} gdasocean_analysis"
```suggestion
            targrp_list="${targrp_list} gdasocean gdasocean_analysis"
```

2023-10-30 19:10 UTC, WalterKolczynski-NOAA approved these changes

2023-10-30 23:58 UTC, merged