Update WAFS package
NOAA-EMC/global-workflow pull request #2018
Opened 2023-11-01 22:38 UTC by YaliMao-NOAA

1. Update WAFS package to produce high resolution WAFS output to meet 2023 ICAO milestone
 2. Update GCIP config file for NESDIS satellite upgrade

# Description

# Type of change

- Bug fix (fixes something broken)
- New feature (adds functionality)
- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? YES/NO
- Does this change require a documentation update? YES/NO

# How has this been tested?

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

2023-11-03 15:24 UTC, KateFriedman-NOAA requested changes
Updates look as discussed. Left comments to make a couple small changes to release notes. Will approve for merge into release branch when addressed. Thanks @YaliMao-NOAA !

2023-11-03 15:24 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.11.md
> +* Change Externals.cfg to tag = "gfs_wafs.v6.3.2"
No need to note this here, the new tag is shown above. Remove the `* Change Externals.cfg to tag = "gfs_wafs.v6.3.2"` line.

2023-11-03 15:24 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.11.md
> +*  No changes from GFS v16.3.10
Remove extra spaces introduced on this line.

2023-11-03 15:54 UTC, aerorahul reviewed
Some comments for your consideration.

2023-11-03 15:54 UTC, aerorahul commented on docs/Release_Notes.gfs.v16.3.11.md
> +This updated config file will be implemented too.
Following the meeting discussion on Nov 3, the NESDIS changes are not going to be included in this release.

2023-11-03 15:54 UTC, aerorahul commented on docs/Release_Notes.gfs.v16.3.11.md
> +Both sides agreed that we sill stop waiting for data from the other side at T+4:45.
```suggestion
Additionally, EMC is updating WAFS ecf definition file to:

1. trigger WAFS blending job 5 min later from 4:25 to 4:30 to compensate for 5-10 min delay in receiving UKMO high resolution data
2. stop producing blended 1.25 deg WAFS file per ICAO milestone. 

Both sides agreed that we sill stop waiting for data from the other side at T+4:45.
```

2023-11-03 15:59 UTC, YaliMao-NOAA commented
Steven didn't approve combining WAFS blending update and GCIP parm update this morning. I am going to make the change to switch back to gfs_wafs.v6.3.1

2023-11-03 17:15 UTC, YaliMao-NOAA commented
The current UK data at DCOM is /lfs/h1/ops/**prod**/dcom/20231103/wgrbbul/ukmet_wafs
The parallel UK data will be /lfs/h1/ops/**para**/dcom/20231103/wgrbbul/ukmet_wafs, which is going to be created Nov 6.

My question is how the parallel run will point to the para DCOM, not the prod DCOM. In global ecflow, which variable is controlling this?

2023-11-06 13:25 UTC, KateFriedman-NOAA approved these changes

2023-11-06 13:28 UTC, merged

2023-12-04 16:09 UTC, YaliMao-NOAA commented on ecf/defs/gfs_v16_3.def
> -                  task jgfs_atmos_wafs_blending
@KateFriedman-NOAA 1.25 deg WAFS blending needs to be added back for https://github.com/NOAA-EMC/global-workflow/pull/2100

2023-12-04 16:45 UTC, KateFriedman-NOAA commented on ecf/defs/gfs_v16_3.def
> -                  task jgfs_atmos_wafs_blending
@YaliMao-NOAA It's in the `gfs_v16_3.def` file for the `release/gfs.v16.3.11` branch: https://github.com/NOAA-EMC/global-workflow/blob/release/gfs.v16.3.11/ecf/defs/gfs_v16_3.def#L1587

It's also in the def file in the `release/gfs.v16.3.12` branch. I undid the WAFS changes in the `release/gfs.v16.3.11` branch and those changes were inherited by the `release/gfs.v16.3.12` branch.

I also see it in the `gfs.v16.3.11` para package on WCOSS2:
```
kate.friedman@clogin06> grep jgfs_atmos_wafs_blending /lfs/h1/ops/para/packages/gfs.v16.3.11/ecf/defs/gfs_v16_3.def
                  task jgfs_atmos_wafs_blending
                  task jgfs_atmos_wafs_blending_0p25
                  task jgfs_atmos_wafs_blending
                  task jgfs_atmos_wafs_blending_0p25
                  task jgfs_atmos_wafs_blending
                  task jgfs_atmos_wafs_blending_0p25
                  task jgfs_atmos_wafs_blending
                  task jgfs_atmos_wafs_blending_0p25
```
...and I see the job in the `gfs.v16.3.11` prod package on Dogwood that the NCO SPA just put into production.

I think we're good, please let me know if I'm missing something.

2023-12-04 16:54 UTC, KateFriedman-NOAA commented on ecf/defs/gfs_v16_3.def
> -                  task jgfs_atmos_wafs_blending
Ignore my prior reply, I see it's missing now but thankfully the ops version has it in `/lfs/h1/ops/prod/packages/gfs.v16.3.11/ecf/defs/gfs_v16_3.def`:
```
                  task jgfs_atmos_wafs_blending
                    trigger ./jgfs_atmos_wafs_grib2 == complete
                    time 04:33
```

2023-12-04 17:20 UTC, YaliMao-NOAA commented on ecf/defs/gfs_v16_3.def
> -                  task jgfs_atmos_wafs_blending
@KateFriedman-NOAA That's good. Cactus hasn't synchronized gfs.v16.3.11 yet so I can't compare the file.

2023-12-04 17:26 UTC, KateFriedman-NOAA commented on ecf/defs/gfs_v16_3.def
> -                  task jgfs_atmos_wafs_blending
@YaliMao-NOAA You can compare the para install of that version on Cactus: `/lfs/h1/ops/para/packages/gfs.v16.3.11/ecf/defs/gfs_v16_3.def`
That's the package that was moved to prod on Dogwood.

2023-12-04 17:36 UTC, YaliMao-NOAA commented on ecf/defs/gfs_v16_3.def
> -                  task jgfs_atmos_wafs_blending
@KateFriedman-NOAA Good. The para version on Cactus includes 1.25 deg WAFS blending. Should I withdraw PR #2113?

2023-12-04 17:38 UTC, KateFriedman-NOAA commented on ecf/defs/gfs_v16_3.def
> -                  task jgfs_atmos_wafs_blending
> Should I withdraw PR https://github.com/NOAA-EMC/global-workflow/pull/2113?
@YaliMao-NOAA Nope, all good! We were missing that change on our end so I've already merged that PR and we're good now. Thanks for catching that in our branch!