Use new GSI tag to turn on data
NOAA-EMC/global-workflow pull request #2102
Opened 2023-11-29 22:25 UTC by ADCollard

This PR turns on active assimilation of NOAA-21 CrIS, NOAA-21 ATMS, GOES-18 Clear Sky Radiances and Metop-C ASCAT.

All substantive changes are confined to the fix directory of GSI and this PR simply checks out the `gfsda.v16.3.12` tag of the GSI.

# How has this been tested?
Clone and build on WCOSS2.  Single cycle test.

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

2023-11-29 22:26 UTC, ADCollard commented
@KateFriedman-NOAA Does the GFS version number get incremented in `versions/run.ver`?  It seems to have been in the past but I am not sure this is correct.

2023-11-30 16:14 UTC, aerorahul commented on docs/Release_Notes.gfs.v16.3.12.md
> +GFS V16.3.11 RELEASE NOTES
```suggestion
GFS V16.3.12 RELEASE NOTES
```

2023-11-30 16:15 UTC, aerorahul requested changes
small typo.

2023-11-30 16:55 UTC, aerorahul approved these changes

2023-11-30 18:35 UTC, KateFriedman-NOAA approved these changes
Looks good and includes expected changes for this. Thanks @ADCollard !

2023-11-30 18:35 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.12.md
> +https://docs.google.com/document/d/18bUYWmsN7FuweyA2CQTBW1rk3FNRMHKPlYHZlbS8ODs/edit?pli=1
These notes were for the prior v16.3.11 upgrade. Am guessing we don't need these in these release notes now.

2023-11-30 18:36 UTC, KateFriedman-NOAA commented
@ADCollard Just one comment, forgot to mention I left it when approving this PR. Please address and we can merge it. Thanks!

2023-11-30 18:45 UTC, ADCollard commented on docs/Release_Notes.gfs.v16.3.12.md
> +https://docs.google.com/document/d/18bUYWmsN7FuweyA2CQTBW1rk3FNRMHKPlYHZlbS8ODs/edit?pli=1
@KateFriedman-NOAA Removed.

2023-11-30 18:45 UTC, ADCollard commented
> @ADCollard Just one comment, forgot to mention I left it when approving this PR. Please address and we can merge it. Thanks!

@KateFriedman-NOAA It should be good now

2023-11-30 18:46 UTC, merged