Update WAFS package to produce high resolution WAFS output to meet 2023 ICAO milestone
NOAA-EMC/global-workflow pull request #2140
Opened 2023-12-11 18:24 UTC by YaliMao-NOAA

WAFS part, a new tag gfs_wafs.v6.3.2
1. Add forecast hour window to dbn_alert for awf and WAFS unblended hazard data
2. Add dbn_alert of not headed non-hazard 1.25 deg data (gfs.tCCz.wafs_grb45fFF.grib2), with subtype GFS_WAFS_1P25_GB2

Global workflow part:
1. Update WAFS tag
2. Update WAFS ecf scripts to set ICAO2023=yes
3. Stop running 1.25 blending
4. Trigger time change of 0.25 blending
5. Increase number of tasks for wafs_grib2_0p25 from 11 to 39, because now we have 39 hours to process when ICAO2023=yes and FHOUT_GFS=1

# Description

# Type of change

- Bug fix (fixes something broken)
- New feature (adds functionality)
- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? YES/NO
- Does this change require a documentation update? YES/NO

# How has this been tested?

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

2023-12-11 18:46 UTC, KateFriedman-NOAA requested changes
Mostly good. I left comments for changes to make in the release notes, as well as another update that is needed to `versions/run.ver`: change `version=v16.3.13` and `gfs_ver=v16.3.13`. Thanks @YaliMao-NOAA !

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +GFS V16.3.11 RELEASE NOTES
Change to "GFS V16.3.13 RELEASE NOTES"

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +
Remove these lines and mention of the GSI. Make sure the PRELUDE states the WAFS updates as you'd like it.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +git clone -b EMC-v16.3.11 https://github.com/NOAA-EMC/global-workflow.git .
Update version to "v16.3.13" on these lines.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +| GSI       | gfsda.v16.3.10 | Andrew.Collard@noaa.gov |
This will be "gfsda.v16.3.12" by the time WAFS going in. Please update the GSI tag name here.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +
Remove these lines, they were for a prior upgrade.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* `versions/build.ver` - change `crtm_ver=2.4.0.1`
Remove this line about `versions/build.ver`.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* `versions/run.ver` - change `version=v16.3.11`, `gfs_ver=v16.3.11` and `crtm_ver=2.4.0.1`
Change this line to be
```
* `versions/run.ver` - change `version=v16.3.13` and `gfs_ver=v16.3.13`
```
Also, update those variables in `versions/run.ver` and commit that change to your PR branch.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* No changes from GFS v16.3.10
Change every instance of "No changes..." to use the prior version:
```
* No changes from GFS v16.3.12
```

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* Changes to sorc/gsi.fd/scripts/exglobal_atmos_analysis.sh
Remove this line referencing a GSI script.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* Changes to `fix/fix_gsi/global_anavinfo.l127.txt`, `fix/fix_gsi/global_satinfo.txt` and add `fix/fix_gsi/Rcov_crisn21`
Replace this line with:
```
* No changes from GFS v16.3.12
```

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* No changes from GFS v16.3.10
See earlier comment.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* No changes from GFS v16.3.10
See earlier comment.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* No changes from GFS v16.3.10
See earlier comment.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +  * GSI & WAFS
Change line to remove mention of GSI.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* No changes from GFS v16.3.10
See earlier comment.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* No changes from GFS v16.3.10
See earlier comment.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* No changes from GFS v16.3.10
See earlier comment.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* No changes from GFS v16.3.10
See earlier comment.

2023-12-11 18:46 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +Jun.Wang@noaa.gov
You can remove Andrew, Wen, and Jun's names from the "PREPARED BY" list. They were in the prior release notes when the GSI and WAFS upgrades were combined. Their names were for the GSI upgrade part.

2023-12-12 16:20 UTC, YaliMao-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* In scripts/exgfs_atmos_wafs_grib2.sh, add dbn_alert of non-headed non-hazard 1.25 deg data (gfs.tCCz.wafs_grb45fFF.grib2) with subtype GFS_WAFS_1P25_GB2
@KateFriedman-NOAA Should this line be in the 'DISSEMINATION INFORMATION' section or stay here?

2023-12-12 16:27 UTC, KateFriedman-NOAA commented on docs/Release_Notes.gfs.v16.3.13.md
> +* In scripts/exgfs_atmos_wafs_grib2.sh, add dbn_alert of non-headed non-hazard 1.25 deg data (gfs.tCCz.wafs_grb45fFF.grib2) with subtype GFS_WAFS_1P25_GB2
Good question...it can stay here. Thanks for checking!

2023-12-12 16:29 UTC, KateFriedman-NOAA approved these changes
Looks great! Thanks for making those edits to the release notes. I approve and will merge now ahead of cutting a hand-off tag.

2023-12-12 16:30 UTC, merged