Reformat snowDA templates to jinja2
NOAA-EMC/global-workflow pull request #2371
Opened 2024-03-02 20:51 UTC by aerorahul

# Description
This PR:
- replaces use of non-jinja2 templates in the yaml templates.  Specifically `$( )` in favor of pure jinja2.
- uses jinja2's built-in capability to include templates within templates, thereby allowing to assemble a completely rendered template before passing it to for e.g. yaml loader.
- requires updates to `wxflow` and `gdasapp`
- Changes in `wxflow` in `parse_j2yaml` are **not** backwards compatible 

Depends on PRs in gdasapp and wxflow:
- https://github.com/NOAA-EMC/GDASApp/pull/947
- https://github.com/NOAA-EMC/wxflow/pull/15

# Type of change
- New feature (adds functionality)
- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? YES [possibly breaks jedi atm, aero]. And soca if it uses `parse_j2yaml`
- Does this change require a documentation update? NO

# How has this been tested?
- SnowDA CI test on Hera

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

2024-03-03 16:02 UTC, jiaruidong2017 reviewed
In `parm/config/gfs/config.prepsnowobs`:
Change:
```
export GTS_OBS_LIST="${HOMEgfs}/sorc/gdas.cd/parm/snow/prep/prep_gts.yaml"
export IMS_OBS_LIST="${HOMEgfs}/sorc/gdas.cd/parm/snow/prep/prep_ims.yaml"
```
TO:
```
export GTS_OBS_LIST="${HOMEgfs}/sorc/gdas.cd/parm/snow/prep/prep_gts.yaml.j2"
export IMS_OBS_LIST="${HOMEgfs}/sorc/gdas.cd/parm/snow/prep/prep_ims.yaml.j2"
```

2024-03-03 16:54 UTC, aerorahul commented
> In `parm/config/gfs/config.prepsnowobs`: Change:
> 
> ```
> export GTS_OBS_LIST="${HOMEgfs}/sorc/gdas.cd/parm/snow/prep/prep_gts.yaml"
> export IMS_OBS_LIST="${HOMEgfs}/sorc/gdas.cd/parm/snow/prep/prep_ims.yaml"
> ```
> 
> TO:
> 
> ```
> export GTS_OBS_LIST="${HOMEgfs}/sorc/gdas.cd/parm/snow/prep/prep_gts.yaml.j2"
> export IMS_OBS_LIST="${HOMEgfs}/sorc/gdas.cd/parm/snow/prep/prep_ims.yaml.j2"
> ```

Thanks for catching this.
Done in [4528c74](https://github.com/NOAA-EMC/global-workflow/pull/2371/commits/4528c741178a003587545a9235431268a0bb91c5)

2024-03-03 17:50 UTC, jiaruidong2017 reviewed
In `parm/config/gfs/config.snowanl`, please make the following changes from the right windows to the left windows as below: 

![image](https://github.com/NOAA-EMC/global-workflow/assets/27369703/828c4275-2b64-4921-a1db-f43f677e99dd)

2024-03-04 01:26 UTC, aerorahul commented
> In `parm/config/gfs/config.snowanl`, please make the following changes from the right windows to the left windows as below:
> 
> ![image](https://private-user-images.githubusercontent.com/27369703/309577370-d4ea37f9-32fa-4f7e-87b8-eac756dbb8dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MTU3ODMsIm5iZiI6MTcwOTUxNTQ4MywicGF0aCI6Ii8yNzM2OTcwMy8zMDk1NzczNzAtZDRlYTM3ZjktMzJmYS00ZjdlLTg3YjgtZWFjNzU2ZGJiOGRjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDAxMjQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYmJiZGI3MDA3ZjkxYmQ5ZDI4OTEzOTNhZGQ5MTk1NzY0MmE5YjYyODVhOGJhMWQzNTAzMDZmOTMwYjgwMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vJUfLIRrF3uVu-uqTzHcEhh8ypAr59kgQIODpxvePqk)

Thanks also for catching this.  I had made the change in my experiment directory but had not committed it to HOMEgfs.
I have reworked some of the logic for the obslist.  
A test is running on Hera at: `/scratch1/NCEPDEV/stmp2/Rahul.Mahajan/RUNTESTS/EXPDIR/snowda`
I will post an update when its complete.

2024-03-04 14:15 UTC, aerorahul commented
@jiaruidong2017 @CoryMartin-NOAA 
I ran the snowDA CI test overnight and it completed successfully.
The experiment and COM directories can be accessed on Hera at:
`/scratch1/NCEPDEV/stmp2/Rahul.Mahajan/RUNTESTS/EXPDIR/snowda` 
`/scratch1/NCEPDEV/stmp2/Rahul.Mahajan/RUNTESTS/COMROOT/snowda`

2024-03-04 14:21 UTC, jiaruidong2017 approved these changes
Thanks for your efforts.

2024-03-04 14:27 UTC, CoryMartin-NOAA approved these changes
Looks good, thanks @aerorahul !

2024-03-04 14:33 UTC, WalterKolczynski-NOAA requested changes
Looks good once the dependent PRs are merged and git modules are updated.

2024-03-04 14:41 UTC, WalterKolczynski-NOAA approved these changes

2024-03-04 16:15 UTC, TerrenceMcGuinness-NOAA commented
Jenkins Artifacts captured appropriate[ error log](https://jenkins.epic.oarcloud.noaa.gov/blue/organizations/jenkins/global-workflow%2FEMC-Global-Pipeline/detail/PR-2371/1/artifacts)

2024-03-04 16:37 UTC, aerorahul commented
The failed test is `C48mx500_3DVarAOWCDA` specifically the `prepoceanobs` task.  
The changes are not likely going to be resolved soon, so we will have to disable this test.

2024-03-04 21:04 UTC, merged

2024-03-15 13:52 UTC, guillaumevernieres commented on ci/cases/pr/C48mx500_3DVarAOWCDA.yaml
> +  - hera
Do you remember what the issue was @aerorahul ?