Fix ensemble archive groups to include all members
NOAA-EMC/global-workflow pull request #2402
Opened 2024-03-14 19:52 UTC by CatherineThomas-NOAA

# Description
The number of groups used in the ensemble archive step (earc) needs to include a task for the ensemble stat files such as the mean and the spread, resulting in `n_groups+1` tasks for `earc`.

Resolves: #2390

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Cycled test on Hera

# Checklist
- [ ] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

2024-03-14 22:01 UTC, WalterKolczynski-NOAA approved these changes

2024-03-15 03:50 UTC, WalterKolczynski-NOAA requested changes, later dismissed

2024-03-15 03:50 UTC, WalterKolczynski-NOAA commented on workflow/rocoto/gfs_tasks.py
> +        groups = ' '.join([f'{grp:02d}' for grp in range(0, n_groups+1)])
For PEP-8 compliance
```suggestion
        groups = ' '.join([f'{grp:02d}' for grp in range(0, n_groups + 1)])
```

2024-03-15 12:14 UTC, CatherineThomas-NOAA commented
@WalterKolczynski-NOAA Thanks for the edit, updated.

2024-03-15 18:33 UTC, aerorahul approved these changes
looks good.

2024-03-15 18:47 UTC, merged