Check the DO_JEDISNOWDA condition before adding snow DA analysis to the list
NOAA-EMC/global-workflow pull request #2471
Opened 2024-04-08 22:08 UTC by jiaruidong2017

# Description
This PR added checking the DO_JEDISNOWDA condition before adding snow DA analysis to the archive list. 

  Resolves #2469 
 
# Type of change

- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

2024-04-08 22:52 UTC, aerorahul requested changes
Thank you for adding the conditional.  This will work.

However, in `config.base`, the variable is named `DO_JEDILANDDA`.  It should be renamed to `DO_JEDISNOWDA`.  Would you mind changing that variable as well to be `DO_JEDISNOWDA` instead of `DO_JEDILANDDA`?

2024-04-08 22:52 UTC, aerorahul commented on ush/hpssarch_gen.sh
> +    if [[ ${DO_JEDISNOWDA} = "YES" ]]; then
```suggestion
    if [[ "${DO_JEDISNOWDA:-}" == "YES" ]]; then
```

2024-04-08 23:46 UTC, jiaruidong2017 commented on ush/hpssarch_gen.sh
> +    if [[ ${DO_JEDISNOWDA} = "YES" ]]; then
Thanks @aerorahul and done the changes as suggested.

2024-04-08 23:59 UTC, jiaruidong2017 commented on ush/hpssarch_gen.sh
> +    if [[ ${DO_JEDISNOWDA} = "YES" ]]; then
Also changed the `DO_JEDILANDDA` to `DO_JEDISNOWDA`.

2024-04-09 14:56 UTC, aerorahul approved these changes
looks good.
At somepoint we should review what needs to be archived for the `sfc_data` files.  We have `sfcanl_data` tile files also being archived.

2024-04-09 18:10 UTC, merged

2024-04-09 18:10 UTC, WalterKolczynski-NOAA approved these changes