Remove implicit symlink names
NOAA-EMC/global-workflow pull request #2527
Opened 2024-04-24 03:17 UTC by WalterKolczynski-NOAA

# Description
Lustre has a defect under Rocky 9 that results in symlink sometimes failing when the link name is not explicit. This updates all link creation to use explicit names.

`config.base` is updated to turn off two monitor jobs on Hercules because the executables are not yet built there. This, combined with the previous change, should make workflow available for use on Hercules.

Also removes the redundant utility names for NCP, NLN, etc. in the gdas scripts that are already defined in `config.base`.

Resolves #2131
Resolves #2522

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
- [x] Cycled atm-only test on Hercules
- [x] Forecast-only S2SWA test on Hercules
- [ ] Full product test on WCOSS2

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

2024-04-24 03:18 UTC, WalterKolczynski-NOAA commented
Not going to do it now, but after MSU comes back from maintenance, will also run this through CI on Hercules.

2024-04-24 11:59 UTC, DavidHuber-NOAA requested changes

2024-04-24 11:59 UTC, DavidHuber-NOAA commented on parm/config/gfs/config.base
> +
Is this an old config.base?  The monitor built for me just fine.

2024-04-24 11:59 UTC, DavidHuber-NOAA commented on ush/wave_grid_interp_sbs.sh
> +    ln -sf "${DATA}/mod_def.${ID}" "mod_def.${ID}"
Would it make sense to replace `ln -sf` with `${NLN}`?

2024-04-24 12:38 UTC, DavidHuber-NOAA commented
It looks like the snowDA test failed as it tried to copy 21Z restart files.  I don't think these should exist for 3dvar experiments.  It seems like `forecast_postdet.sh` should be keying on `iaufhrs` instead of `restart_interval`.

2024-04-24 14:46 UTC, DavidHuber-NOAA commented
> It looks like the snowDA test failed as it tried to copy 21Z restart files. I don't think these should exist for 3dvar experiments. It seems like `forecast_postdet.sh` should be keying on `iaufhrs` instead of `restart_interval`.

Actually, I think the proper solution is to modify the `restart_interval` based on `DOHYBVAR` (3 if `DOHYBVAR`, else 6) in config.fcst.

2024-04-24 16:25 UTC, WalterKolczynski-NOAA commented on parm/config/gfs/config.base
> +
`build_all.sh` still turns it off if you are on Hercules. If it is working, I will take that out and remove this bit.

2024-04-24 16:26 UTC, WalterKolczynski-NOAA commented on ush/wave_grid_interp_sbs.sh
> +    ln -sf "${DATA}/mod_def.${ID}" "mod_def.${ID}"
That probably would've been smart. I was trying to make minimal ancillary changes.

2024-04-25 16:26 UTC, aerorahul approved these changes
looks good.  did not test.

2024-04-25 16:41 UTC, DavidHuber-NOAA approved these changes
Looks good, thanks!

2024-04-26 18:44 UTC, WalterKolczynski-NOAA commented
`gfswavepostpnt` is hanging during the MPMD on Hercules. Works on other machines. @DavidHuber-NOAA is taking a look since he didn't see it during the original Hercules port.

2024-04-26 18:46 UTC, JessicaMeixner-NOAA commented
@WalterKolczynski-NOAA @DavidHuber-NOAA - Let me know if you need a waves person to take a look.

2024-04-26 20:06 UTC, DavidHuber-NOAA commented
After some digging, I found the following error in two members of an MPMD job:
```
slurmstepd: error: *** STEP 1084715.0 STEPD TERMINATED ON hercules-03-46 AT 2024-04-25T18:17:33 DUE TO JOB NOT ENDING WITH SIGNALS ***
```

Based on log output, all of the subtasks completed successfully, but some of the members seem to not be returning proper statuses to `srun`, which causes the job to stall.  It's not clear what is causing this to happen.  I've forwarded this information to the Hercules helpdesk.

2024-04-30 20:37 UTC, merged