Implement global-workflow on AWs
NOAA-EMC/global-workflow pull request #2549
Opened 2024-04-27 01:49 UTC by weihuang-jedi

PRs should meet these guidelines:
    - Each PR should address ONE topic and have an associated issue.
    - No hard-coded paths or personal directories.
    - No temporary or backup files should be committed (including logs).
    - Any code that you disabled by being commented out should be removed or reenabled.

    Please delete all these comments before submitting the PR.
-->
# Description
 This PR implement global-workflow on AWS.

  Resolves https://github.com/NOAA-EPIC/global-workflow-cloud/issues/2
  
# Type of change
- New feature (adds functionality)

# Change characteristics
- Does this change require a documentation update? YES

# How has this been tested?
Tested on AWS

Example:
- Clone and build on AWS

# Checklist
- [x ] Code changes for GSI-Utils
- [ ] Code changes for UFS-Utils
- [ ] Code Changes for GFS-Utils
- [x ] Code changes for GSI-monitor
- [ ] Code changes for UPP
- [ ] Code changes for UFS-weather-model
- [ ] Code changes for GSI
- [ ] Code changes for GDAS

2024-04-27 02:01 UTC, weihuang-jedi commented
This is at its early stage, depends on many things. Will mark it ready when things all settled.

2024-05-01 11:38 UTC, DavidHuber-NOAA commented on parm/config/gfs/config.resources
@weihuang-jedi This is probably a little early, but I wanted to point out that when you get to testing cycling, you will want to be careful about how you assign resources for the eobs and anal jobs.  Both of these jobs have bugs in them that cause data to be unassimilated if `npe_node` is not equal to the number of tasks on each node.  See the notes under both jobs in config.resources and issue #2092 for more details.

2024-05-01 13:29 UTC, weihuang-jedi commented
Thanks for the heads up.
Yes, I need to be more careful and take care of those situations.
Probably will need a short program to check machine CPUs, and set those
when setup the case.
Let us keep our eyes open on such issue.


On Wed, May 1, 2024 at 5:39 AM David Huber ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> On parm/config/gfs/config.resources
> <https://github.com/NOAA-EMC/global-workflow/pull/2549#discussion_r1586215191>
> :
>
> @weihuang-jedi <https://github.com/weihuang-jedi> This is probably a
> little early, but I wanted to point out that when you get to testing
> cycling, you will want to be careful about how you assign resources for the
> eobs and anal jobs. Both of these jobs have bugs in them that cause data to
> be unassimilated if npe_node is not equal to the number of tasks on each
> node. See the notes under both jobs in config.resources and issue #2092
> <https://github.com/NOAA-EMC/global-workflow/issues/2092> for more
> details.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NOAA-EMC/global-workflow/pull/2549#pullrequestreview-2033486199>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ASMCH6ZP7VWSZEUCEGW7DJDZADH6DAVCNFSM6AAAAABG3VK7VGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMZTGQ4DMMJZHE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-06-14 22:19 UTC, aerorahul requested changes
Please describe the hard to understand updates in this PR.
Please see specific comments.

2024-06-14 22:19 UTC, aerorahul commented on .gitmodules
> +  url = https://github.com/ufs-community/ufs-weather-model.git
please revert.

2024-06-14 22:19 UTC, aerorahul commented on env/AZUREPW.env
> +#! /usr/bin/env bash
Please remove Azure and Google additions from this PR as this PR is titled "Implemente global-workflow on AWS"

2024-06-14 22:19 UTC, aerorahul commented on parm/config/gfs/config.base
> +export DO_GENESIS_FSU="NO" # Cyclone genesis verification (FSU)
Please revert.

2024-06-14 22:19 UTC, aerorahul commented on parm/config/gfs/config.resources
> +    npe_node_max=30
Please withhold till these platforms are available and the workflow is being ported to them.

2024-06-14 22:19 UTC, aerorahul commented on parm/config/gfs/config.resources
> +    export wtime_atmos_products="01:15:00"
This is a significant increase.
Please revert.

2024-06-14 22:19 UTC, aerorahul commented on parm/config/gfs/config.resources
> +    export wtime_verfozn="00:15:00"
Can this be explained?

2024-06-14 22:19 UTC, aerorahul commented on parm/config/gfs/config.stage_ic
> +    fi
Why is the canned ICs stored in a different directory naming structure on the cloud? This seems unnecessary

2024-06-14 22:19 UTC, aerorahul commented on scripts/exglobal_stage_ic.sh
> +      fi
This is not correct.

2024-06-14 22:19 UTC, aerorahul commented on scripts/exglobal_stage_ic.sh
> +       #tgt="${COM_ATMOS_RESTART_PREV}/${PDY}.${cyc}0000.${ftype}.tile${tt}.nc"
Please remove commented lines.

2024-06-14 22:19 UTC, aerorahul commented on scripts/exglobal_stage_ic.sh
> +        fi
If target is present, it should overwrite.  What happens if the source has changed?

2024-06-14 22:19 UTC, aerorahul commented on scripts/exglobal_stage_ic.sh
> +
Why are there changes in this script?  How are they related to porting the workflow to AWS?

2024-06-14 22:19 UTC, aerorahul commented on sorc/com.slurm
> +#!/bin/bash
Please remove this file.

2024-06-14 22:19 UTC, aerorahul commented on sorc/gdas.cd
Please do not update submodules to which capability is not available on AWS.

2024-06-14 22:19 UTC, aerorahul commented on sorc/setup-case.sh
> +#!/bin/bash
Please delete this file.

2024-06-14 22:19 UTC, aerorahul commented on versions/run.noaacloud.ver
> +#export spack_env=unified-env
please remove this line

2024-06-14 22:19 UTC, aerorahul commented on versions/run.noaacloud.ver
> +export ncl_ver=6.6.2
NCL is not used on the cloud or in the workflow

2024-06-14 22:19 UTC, aerorahul commented on versions/run.noaacloud.ver
> +#export R_ver=4.0.2
Please remove

2024-06-14 22:19 UTC, aerorahul commented on versions/run.noaacloud.ver
> +export spack_mod_path="/work/noaa/epic/role-epic/spack-stack/orion/spack-stack-${spack_stack_ver}/envs/${spack_env}/install/modulefiles/Core"
This is an orion line.  Please remove.

2024-06-14 22:19 UTC, aerorahul commented on workflow/hosts.py
> +                       'AWSPW', 'AZUREPW', 'GOOGLEPW']
Please remove Azure and Google.

2024-06-14 22:19 UTC, aerorahul commented on workflow/hosts/awspw.yaml
> +NOSCRUB: '/contrib/${USER}/scrub'
Duplicate line

2024-06-14 22:19 UTC, aerorahul commented on workflow/hosts/awspw.yaml
> +IC_TYPE: 'input'
These are not host specific and should not be in this file.

2024-06-14 22:19 UTC, aerorahul commented on workflow/hosts/awspw.yaml
> +ACCOUNT: $USER
Duplicate

2024-06-14 22:19 UTC, aerorahul commented on workflow/hosts/azurepw.yaml
> +BASE_GIT: '/work/noaa/global/glopara/git'
Please remove this file from this PR.

2024-06-14 22:19 UTC, aerorahul commented on workflow/hosts/azurepw.yaml
> +BASE_GIT: '/work/noaa/global/glopara/git'
These are Orion paths.

2024-06-14 22:19 UTC, aerorahul commented on workflow/hosts/googlepw.yaml
> +BASE_GIT: '/work/noaa/global/glopara/git'
Please remove this file.
These are orion paths

2024-06-14 22:19 UTC, aerorahul commented on workflow/rocoto/gfs_tasks.py
> +                prefix = f"{icdir}/{cpl_ic_prefix}.@Y@m@d/@H/model_data/atmos/{cpl_ic_type}"
This should not be needed.

2024-06-14 22:19 UTC, aerorahul commented on workflow/rocoto/rocoto.py
> +    if pw_csp not in ['aws', 'azure', 'google']:
rocoto.py need not know if this is PW_CSP.
Please outline the issue and we can discuss.

2024-06-14 22:19 UTC, aerorahul commented on workflow/rocoto/tasks.py
> +                native = '--export=NONE'
This should be handled elsewhere.

2024-06-14 22:19 UTC, aerorahul commented on workflow/rocoto/workflow_xml.py
> +                  ''])
Can you describe the reason here

2024-06-14 23:18 UTC, HenryWinterbottom-NOAA commented
@weihuang-jedi Please properly follow the PR template guidelines. See, for example, https://github.com/NOAA-EMC/global-workflow/pull/2688.

2024-06-25 14:51 UTC, DavidHuber-NOAA commented
Should this be closed in favor of #2711?

2024-06-25 16:57 UTC, closed without merging

2024-06-25 16:57 UTC, aerorahul commented
Closing in favor of #2711