Updated GEMPAK version and APRUN launcher.
NOAA-EMC/global-workflow pull request #2555
Opened 2024-04-29 21:09 UTC by HenryWinterbottom-NOAA

# Description

This PR addresses issue #2248 and #2513. The following is accomplished:

- Updates the parallel executable for GEMPAK applications;
- Updates the GEMPAK version for RDHPCS Hera.

  Describe your changes. Focus on the *what* and *why*. The *how* will be evident from the changes. In particular, be sure to note any interface changes, such as command line syntax, that will need to be communicated to users.

  At the end of your description, please be sure to add the issue this PR solves using the word "Resolves". If there are any issues that are related but not yet resolved (including in other repos), you may use "Refs".

  Resolves #2248 
  Resolves #2513 

# Type of change

- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?

Tested on RDHPCS Hera. The following is the Rocoto status:

```
       CYCLE                    TASK                       JOBID               STATE         EXIT STATUS     TRIES      DURATION
================================================================================================================================
202103231200               gfsgempak                    58973651           SUCCEEDED                   0         1         526.0
```

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

2024-04-29 21:10 UTC, HenryWinterbottom-NOAA commented
@DavidHuber-NOAA This addresses only RDHPCS Hera. I want to make sure this addresses all points in #2248 before I update the remaining platforms.

2024-04-30 02:27 UTC, WalterKolczynski-NOAA commented
There should be more gempak jobs than just one.

2024-04-30 15:32 UTC, DavidHuber-NOAA requested changes
@HenryWinterbottom-NOAA It looks like this was indirectly fixed by @WalterKolczynski-NOAA in #2374.  The GEMPAK jobs now call `ush/run_mpmd.sh` to run their MPMD jobs.  Within run_mpmd.sh, it keys off of `launcher` instead of `APRUN` (or any variety of `APRUN*`).

So instead, I think the correct action is to remove `APRUN` definitions from all of the `env` files.

2024-04-30 15:32 UTC, DavidHuber-NOAA commented on env/HERA.env
> +    export APRUN_GEMPAKCFP="${launcher} -n ${npe_gempak} ${mpmd_opt}"
```suggestion
```

2024-04-30 15:36 UTC, DavidHuber-NOAA commented
To clarify, by "remove all of the `APRUN` definitions`, I'm referring to just the GEMPAK job.

2024-05-01 11:42 UTC, DavidHuber-NOAA approved these changes
Looks good, thanks!

2024-05-02 00:13 UTC, merged