Script to keep Jenkins Agent persistent from cron
NOAA-EMC/global-workflow pull request #2634
Opened 2024-05-28 21:38 UTC by TerrenceMcGuinness-NOAA

# Description

This "persistent" Java Agent launch script can be ran from a cron job:
Uses Jenkins Remote API to check the status of the Node connection using curl for a given machine.
If it is not connected a new agent is launched for that node.

Resloves #2633

# Type of change
- New feature (adds a more robust capability)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
Script was run on Orion, Hera, and Hercules and each could determine that the nodes where up and nothing was done.

2024-05-28 21:54 UTC, WalterKolczynski-NOAA requested changes
Looks good. Thanks for getting this done so quickly.

Don't think there is any point in running CI on this, so I'll merge once the indentation is corrected.

2024-05-28 21:54 UTC, WalterKolczynski-NOAA commented on ci/scripts/utils/launch_java_agent.sh
> +   ;;
```suggestion
  hera | orion | hercules | wcoss2)
    echo "Launch Jenkins Java Controler on ${MACHINE_ID}"
    ;;
  *)
    echo "Unsupported platform. Exiting with error."
    exit 1
    ;;
```

2024-05-29 15:04 UTC, TerrenceMcGuinness-NOAA commented
@WalterKolczynski-NOAA Yes this script was greatly needed and really cleans a lot of stuff up with launching by making it uniform and defined in the repo.  BTW, I'm contributing using AI that has made these one day turn around times for these solutions.

2024-05-29 17:00 UTC, WalterKolczynski-NOAA approved these changes

2024-05-29 17:00 UTC, merged