Fix and simplify online archiving #2673
NOAA-EMC/global-workflow pull request #2687
Opened 2024-06-13 17:31 UTC by DavidHuber-NOAA

# Description
This fixes the online archiving portion of the `*arch` and `*earc00` jobs.

The approach previously taken created `FileHandler` dictionaries at varying levels within the resulting yaml, which was not properly parsed by `exglobal_archive.py`.  This approach creates a single `FileHandler` dictionary and is much less complicated overall.

Resolves #2673

# Type of change
- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
C96C48_hybatmDA test on Hera

# Checklist
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes

2024-06-13 17:32 UTC, DavidHuber-NOAA commented
This is also a prerequisite for https://github.com/NOAA-EMC/global-workflow/issues/2647.

2024-06-13 17:45 UTC, aerorahul commented
@DavidHuber-NOAA 
Please plan on updating this branch once #2668 is merged.

2024-06-17 21:55 UTC, WalterKolczynski-NOAA requested changes

2024-06-17 21:55 UTC, WalterKolczynski-NOAA commented on parm/archive/arcdir.yaml.j2
> +    {% endif %}
I would move this to the end where you are also listing the copy files

2024-06-18 15:32 UTC, DavidHuber-NOAA commented
Merged in the changes from #2668 and I'm now rerunning a `C96C48_hybatmDA` test case on Hera.  I will notify when it is finished.

2024-06-18 16:13 UTC, emilyhcliu commented
@DavidHuber-NOAA I just setup the global-workflow with your fix/archive branch which you just merged from develop earlier this morning.  

```
commit 3329fe7f8eab53a7983fba9a2c148399843f3bfd (HEAD -> fix/archive, DavidHuber/fix/archive)
Merge: 79c333c4 35d4d99e
Author: DavidHuber <david.huber@noaa.gov>
Date:   Tue Jun 18 15:10:16 2024 +0000

    Merge remote-tracking branch 'origin/develop' into fix/archive

```
I set DO_METP = YES
I am running a short cycle experiment from your branch on HERA:
HOMEgfs: /scratch1/NCEPDEV/da/Emily.Liu/git/Global-Workflow/global-workflow-archivefix
EXPDIR:  /scratch1/NCEPDEV/da/Emily.Liu/para/v17/v17test
ROTDIRS: /scratch2/NCEPDEV/stmp3/Emily.Liu/ROTDIRS/v17test
RUNDIRS: /scratch1/NCEPDEV/stmp2/Emily.Liu/RUNDIRS/v17test
ARCDIR: /scratch1/NCEPDEV/da/Emily.Liu/archive/v17test 

The run just started.  
Reviews can check if the archive works expected.

2024-06-18 17:05 UTC, WalterKolczynski-NOAA approved these changes
Conditionally approved

2024-06-18 21:23 UTC, emilyhcliu commented
The test parallel experiment `c17test` failed at it first gdas and gfs archiving jobs.
Here are the log files:
/scratch2/NCEPDEV/stmp3/Emily.Liu/ROTDIRS/v17test/logs/2023040200/gdasarch.log
/scratch2/NCEPDEV/stmp3/Emily.Liu/ROTDIRS/v17test/logs/2023040200/gfsarch.log

Here is the error message from gfsarch.log:
```
jinja2.exceptions.TemplateSyntaxError: expected token ',', got '{'
+ JGLOBAL_ARCHIVE[1]: postamble JGLOBAL_ARCHIVE 1718741136 1
+ preamble.sh[70]: set +x
End JGLOBAL_ARCHIVE at 20:05:58 with error code 1 (time elapsed: 00:00:22)
```

2024-06-19 00:31 UTC, emilyhcliu commented
The EnKF archive jobs failed as well.
/scratch2/NCEPDEV/stmp3/Emily.Liu/ROTDIRS/v17test/logs/2023040200/enkfgdasearc01.log

```
Traceback (most recent call last):
  File "/scratch1/NCEPDEV/da/Emily.Liu/git/Global-Workflow/global-workflow-archivefix/scripts/exgdas_enkf_earc.py", line 60, in <module>
    main()
  File "/scratch1/NCEPDEV/da/Emily.Liu/git/Global-Workflow/global-workflow-archivefix/ush/python/wxflow/logger.py", line 266, in wrapper
    retval = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/da/Emily.Liu/git/Global-Workflow/global-workflow-archivefix/scripts/exgdas_enkf_earc.py", line 47, in main
    arcdir_set, atardir_sets = archive.configure(archive_dict)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/da/Emily.Liu/git/Global-Workflow/global-workflow-archivefix/ush/python/wxflow/logger.py", line 266, in wrapper
    retval = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/da/Emily.Liu/git/Global-Workflow/global-workflow-archivefix/ush/python/pygfs/task/archive.py", line 87, in configure
    arcdir_set = Archive._construct_arcdir_set(arcdir_j2yaml,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/da/Emily.Liu/git/Global-Workflow/global-workflow-archivefix/ush/python/wxflow/logger.py", line 266, in wrapper
    retval = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/da/Emily.Liu/git/Global-Workflow/global-workflow-archivefix/ush/python/pygfs/task/archive.py", line 353, in _construct_arcdir_set
    arcdir_set = parse_j2yaml(arcdir_j2yaml,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/da/Emily.Liu/git/Global-Workflow/global-workflow-archivefix/ush/python/wxflow/yaml_file.py", line 185, in parse_j2yaml
    return YAMLFile(data=Jinja(path, data, searchpath=searchpath, allow_missing=allow_missing).render)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/da/Emily.Liu/git/Global-Workflow/global-workflow-archivefix/ush/python/wxflow/jinja.py", line 198, in render
    return render_map[self.template_type]()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/da/Emily.Liu/git/Global-Workflow/global-workflow-archivefix/ush/python/wxflow/jinja.py", line 209, in _render_file
    template = env.get_template(self.template_file)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev-rocky8/install/intel/2021.5.0/py-jinja2-3.1.2-3yb4fme/lib/python3.11/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev-rocky8/install/intel/2021.5.0/py-jinja2-3.1.2-3yb4fme/lib/python3.11/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev-rocky8/install/intel/2021.5.0/py-jinja2-3.1.2-3yb4fme/lib/python3.11/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev-rocky8/install/intel/2021.5.0/py-jinja2-3.1.2-3yb4fme/lib/python3.11/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/scratch1/NCEPDEV/nems/role.epic/spack-stack/spack-stack-1.6.0/envs/gsi-addon-dev-rocky8/install/intel/2021.5.0/py-jinja2-3.1.2-3yb4fme/lib/python3.11/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/scratch1/NCEPDEV/da/Emily.Liu/git/Global-Workflow/global-workflow-archivefix/parm/archive/arcdir.yaml.j2", line 61, in template
    {% do det_anl_files.append([COMIN_OBS ~ "/" ~ head ~ "aeroawobs",
^^^^^^^^^^^^^^^^^^^^^
jinja2.exceptions.TemplateSyntaxError: expected token ',', got '{'
+ JGDAS_ENKF_ARCHIVE[1]: postamble JGDAS_ENKF_ARCHIVE 1718752225 1
+ preamble.sh[70]: set +x
End JGDAS_ENKF_ARCHIVE at 23:10:51 with error code 1 (time elapsed: 00:00:26)
```

2024-06-20 12:21 UTC, DavidHuber-NOAA commented
@emilyhcliu Thanks for the catch.  It seems I missed a couple closing parentheses and curly braces.  I have added them and am restarting my test after a merge with develop.

2024-06-20 16:14 UTC, emilyhcliu commented
> @emilyhcliu Thanks for the catch. It seems I missed a couple closing parentheses and curly braces. I have added them and am restarting my test after a merge with develop.

@DavidHuber-NOAA Thanks for fixing the errors.  I will update my branch and rewind the archive jobs.  I will report back here.

2024-06-20 16:41 UTC, DavidHuber-NOAA commented
@emilyhcliu @malloryprow I enabled the METplus jobs in my test and turned them on by default.  After running through the first full GFS cycle, I verified that the `gdas`, `gfs`, and `enkfgdas` `pgb`, `gsistat`, `enkfstat`, `storms`, and `trak` files were sent to the online archive and that the `metp` jobs ran successfully (the first cycle only runs Grid2Grid and Grid2Obs; Precip will run on the next full GFS cycle).

I have updated the description of this PR to also resolve #2647.  Please feel free to take a look at the experiment setup, logs, online archive, and METplus outputs:

| Directory Name | Path |
| ----- | ------|
| EXPDIR | /scratch1/NCEPDEV/global/David.Huber/para/EXPDIR/db_arch |
| COMROOT | /scratch1/NCEPDEV/global/David.Huber/para/COMROOT/db_arch |
| ARCDIR | /scratch1/NCEPDEV/global/David.Huber/archive/db_arch |
| METplusOUT | | ARCDIR | /scratch1/NCEPDEV/global/David.Huber/archive/metplus_data/by_VSDB/*/*/00Z/db_arch |

2024-06-20 16:49 UTC, malloryprow commented
METplus output looks like what I would expect for the first day's run and a 00Z GFS cycle. 👍

2024-06-20 17:00 UTC, emilyhcliu commented
@DavidHuber-NOAA Thanks for running the test. 
I checked the online archive for the GDAS and GFS for the first cycle
1. The GDAS analysis, the 9-hourly forecast, and the gsistat/enkfstat are archived OK.
2. The GFS analysis, the 3-hourly forecast up to 5 days, and the gsistat file are archived OK.

2024-06-20 17:41 UTC, DavidHuber-NOAA commented
The second GFS cycle completed and all METplus jobs appear to have completed successfully, including Precip, which produced `/scratch1/NCEPDEV/global/David.Huber/archive/metplus_databy_VSDB/precip/ccpa_accum24hr/00Z/db_arch/db_arch_20211222.stat`.  @malloryprow Could you check this file to make sure it is valid?

2024-06-21 12:49 UTC, DavidHuber-NOAA commented
Starting CI testing.

2024-06-21 13:42 UTC, emilyhcliu approved these changes

2024-06-21 14:33 UTC, aerorahul commented
> Experiment C96_atmaerosnowDA **FAILED** on Hera with error logs:
> 
> ```
> /scratch1/NCEPDEV/global/CI/2687/RUNTESTS/COMROOT/C96_atmaerosnowDA_56009241/logs/2021122018/gdasprepsnowobs.log
> ```
> 
> Follow link here to view the contents of the above file(s): [(link)](https://gist.github.com/emcbot/d5b0dadcb1a1485d1da160970e585bb5)

The hash is `56009241` and `datetime.strptime` is trying to convert this to a `datetime` object with some regex stuff. This was encountered before and a IODA-converters had an issue that seems resolved. https://github.com/JCSDA-internal/ioda-converters/issues/1497
@CoryMartin-NOAA @jiaruidong2017 any thoughts?

2024-06-21 15:09 UTC, DavidHuber-NOAA commented
@aerorahul @CoryMartin-NOAA @jiaruidong2017 A simple fix would be to replace the `re` call with
```python
str_date = re.findall(r'\d{8}', filename)[-1]
```
What do you think?

2024-06-21 15:13 UTC, CoryMartin-NOAA commented
I think we just need to update the GDASApp to point to a more recent ioda-converters hash, then this should (hopefully) be resolved

2024-06-21 17:19 UTC, DavidHuber-NOAA commented
@aerorahul Manually checking the other CI tests on Hera, they all passed.  I believe this PR is now ready to be merged.

2024-06-21 17:29 UTC, aerorahul commented
Thanks @DavidHuber-NOAA 
I see @emilyhcliu has approved and confirmation comments from @malloryprow 
Feel free to merge.

2024-06-21 17:29 UTC, aerorahul approved these changes
Looks good.
Thanks for the updates and thank you to the reviewers @emilyhcliu @malloryprow

2024-06-21 17:44 UTC, merged