Update omega calculation
NOAA-EMC/global-workflow pull request #2751
Opened 2024-07-08 17:27 UTC by XiaqiongZhou-NOAA

-->
# Description

# Type of change

- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

2024-07-08 17:35 UTC, DavidHuber-NOAA reviewed
Does this PR need to update the UFS hash to https://github.com/ufs-community/ufs-weather-model/commit/8e7b61b197f777328464eb2e7dbd006c6c148829 to capture this new feature?

2024-07-08 17:37 UTC, XiaqiongZhou-NOAA commented
Yes, otherwise, the new namelist parameter added can not be recognized by the model.

2024-07-08 17:45 UTC, DavidHuber-NOAA commented
@XiaqiongZhou-NOAA Would you be able to update the hash in the PR, then?

2024-07-08 17:49 UTC, aerorahul commented
FYI @JessicaMeixner-NOAA @NeilBarton-NOAA 
This update will change the current default settings for GFSv17 and GEFSv13.

2024-07-08 17:52 UTC, JessicaMeixner-NOAA commented
@XiaqiongZhou-NOAA - I do not see this parameter updated in the GFSv17 tests in the PR you mentioned https://github.com/ufs-community/ufs-weather-model/pull/2327   So I'm a little concerned about changing answers here when we don't have the corresponding changes in the GFSv17 tests in ufs-weather-model. 

Also FYI to @CatherineThomas-NOAA

2024-07-08 17:56 UTC, XiaqiongZhou-NOAA commented
> @XiaqiongZhou-NOAA - I do not see this parameter updated in the GFSv17 tests in the PR you mentioned [ufs-community/ufs-weather-model#2327](https://github.com/ufs-community/ufs-weather-model/pull/2327) So I'm a little concerned about changing answers here when we don't have the corresponding changes in the GFSv17 tests in ufs-weather-model.
> 
> Also FYI to @CatherineThomas-NOAA

This is not updated in ufs-weather-model. We would wait for the tests to see the impact on HAFS and RRFS. It was tested for GFSv17 and I will talk more on GFSv17/GEFSv13 meeting tomorrow.

2024-07-08 18:05 UTC, JessicaMeixner-NOAA commented
The GFSv17 tests https://docs.google.com/document/d/1usaJk0KmZAl7rNAVNojZD6-7lnbMVWXcLL6P6mIchMI/edit?usp=sharing and https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/rt.conf#L38-L39 are just settings for GFSv17 and do not have impact on HAFS or RRFS.  Adding the setting updates here means that we ensure the new settings meet the reproducibility and other settings.

2024-07-08 18:09 UTC, XiaqiongZhou-NOAA commented
> The GFSv17 tests https://docs.google.com/document/d/1usaJk0KmZAl7rNAVNojZD6-7lnbMVWXcLL6P6mIchMI/edit?usp=sharing and https://github.com/ufs-community/ufs-weather-model/blob/develop/tests/rt.conf#L38-L39 are just settings for GFSv17 and do not have impact on HAFS or RRFS. Adding the setting updates here means that we ensure the new settings meet the reproducibility and other settings.

We plan to set this parameter =. true. as the default for all applications not just for GFSv17, so would like to see the impact on HAFS/RRFS before we change the setting for all regression tests.

2024-07-08 18:59 UTC, JessicaMeixner-NOAA commented
@XiaqiongZhou-NOAA before we use this in the global-workflow, we should have this turned on in the regression tests for GFSv17 in ufs-weather-model.  It can always be subsequently updated for other systems as well.

2024-07-08 19:10 UTC, XiaqiongZhou-NOAA commented
> @XiaqiongZhou-NOAA before we use this in the global-workflow, we should have this turned on in the regression tests for GFSv17 in ufs-weather-model. It can always be subsequently updated for other systems as well.

I agree this is an option. Please update

2024-07-08 20:28 UTC, JessicaMeixner-NOAA requested changes
We need to make sure this has been tested in ufs-waether-model GFSv17 tests before moving forward with this PR.

2024-07-29 17:55 UTC, yangfanglin commented
> We need to make sure this has been tested in ufs-waether-model GFSv17 tests before moving forward with this PR.

@XiaqiongZhou-NOAA   Kate, what is the status of this PR ?  Were you able to update the ufs-weather-model RTs ?  If not, what is blocking the update ?

2024-07-29 17:57 UTC, XiaqiongZhou-NOAA commented
> Corresponding parameter changed in GFSv17 related regression tests (PR#[2373](https://github.com/ufs-community/ufs-weather-model/pull/2373))

2024-08-01 14:21 UTC, XiaqiongZhou-NOAA commented
The namelist related to this PR was changed in the regression tests and PR 2373 (https://github.com/ufs-community/ufs-weather-model/pull/2373) was merged to ufs_model . Please update the workflow.

2024-08-02 00:00 UTC, aerorahul commented
@XiaqiongZhou-NOAA Please resolve the conflicts and ensure the hash of the ufs_model.fd is the right one you wish to use with this branch.  Thanks!

2024-08-06 15:03 UTC, WalterKolczynski-NOAA submitted a review, later dismissed
Conditionally approved

2024-08-06 15:04 UTC, WalterKolczynski-NOAA commented
@XiaqiongZhou-NOAA Pull in the most recent develop changes and this is ready to run through CI

2024-08-09 08:19 UTC, WalterKolczynski-NOAA commented
Failed on WCOSS after the model blew up:
```
FATAL from PE     1: NaN in input field of mpp_reproducing_sum(_2d), this indicates numerical instability
```

2024-08-09 15:57 UTC, XiaqiongZhou-NOAA commented
> /work2/noaa/stmp/CI/HERCULES/2751/RUNTESTS/COMROOT/C96_atm3DVar_2f9d291a/logs/2021122100/gdasverfozn.log

It failed due to time limit.

2024-08-09 16:07 UTC, XiaqiongZhou-NOAA commented
> Failed on WCOSS after the model blew up:
> 
> ```
> FATAL from PE     1: NaN in input field of mpp_reproducing_sum(_2d), this indicates numerical instability
> ```
When the new parameter added was set to pass_full_omega_to_physics_in_non_hydrostatic_mode = .false., it reproduces the old results. The model does not crash but still see a lot of temperature warning. It seems that the original configuration is quite unstable. Very minor changes could possibly result into model crash. It is difficult to point out which is responsible for that so far.

2024-08-09 20:24 UTC, CatherineThomas-NOAA commented
This is a problem that we've encountered before with the testing of PR #2732 where the failure at C48 only occurred on WCOSS2 and not Hera.  @RuiyuSun will do some additional investigation to make sure that the configuration for both machines are as expected.

2024-08-12 18:04 UTC, RuiyuSun commented
> > Failed on WCOSS after the model blew up:
> > ```
> > FATAL from PE     1: NaN in input field of mpp_reproducing_sum(_2d), this indicates numerical instability
> > ```
> 
> When the new parameter added was set to pass_full_omega_to_physics_in_non_hydrostatic_mode = .false., it reproduces the old results. The model does not crash but still see a lot of temperature warning. It seems that the original configuration is quite unstable. Very minor changes could possibly result into model crash. It is difficult to point out which is responsible for that so far.

I reproduced the failure on WCOSS2 (cactus) and completed the same case on Hera. Both  pass_full_omega_to_physics_in_non_hydrostatic_mode was set to .true.. I say a bunch range warning message in the log file on cactus but not on Hera.  Really strange.

2024-08-12 18:08 UTC, RuiyuSun commented
I re-run the case on both Cactus and Hera. The one on Cactus failed and the one on Hera completed successfully. I compared ICs, restart files and some fix files, namelist  variables specified in input.nml and ice_in. So far I haven't found any difference, except for the locations of some fix files given in the input.nml (expected).

2024-08-13 16:13 UTC, RuiyuSun commented
> I re-run the case on both Cactus and Hera. The one on Cactus failed and the one on Hera completed successfully. I compared ICs, restart files and some fix files, namelist variables specified in input.nml and ice_in. So far I haven't found any difference, except for the locations of some fix files given in the input.nml (expected).

details of the comparison: 

Comparisons of restart files: 
Ice : same 
(base) [Ruiyu.Sun@hfe07 restart]$ nccmp -d 20210323.120000.cice_model.res.nc /scratch1/NCEPDEV/stmp2/Ruiyu.Sun/ROTDIRS/s2sw1/gdas.20210323/06/model_data/ice/restart/20210323.120000.cice_model.res.nc
Wave : same 
(base) [Ruiyu.Sun@hfe06 restart]$ pwd
/scratch1/NCEPDEV/stmp2/Ruiyu.Sun/ROTDIRS/s2sw1/gfs.20210323/06/model_data/wave/restart
(base) [Ruiyu.Sun@hfe06 restart]$ cmp 20210323.120000.restart.uglo_100km 20210323.120000.restart.uglo_100km.cactus


Ocean: same 
(base) [Ruiyu.Sun@hfe07 restart]$ nccmp -d 20210323.120000.MOM.res.nc /scratch1/NCEPDEV/stmp2/Ruiyu.Sun/ROTDIRS/s2sw1/gdas.20210323/06/model_data/ocean/restart/20210323.120000.MOM.res.nc
(base) [Ruiyu.Sun@hfe07 restart]$ pwd
/scratch1/NCEPDEV/stmp2/Ruiyu.Sun/ROTDIRS/s2sw1/gdas.20210323.cactus.ocean.ice/06/model_data/ocean/restart

ATM ICs: same 
(base) [Ruiyu.Sun@hfe06 input.cactus]$ module load nccmp
(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d gfs_ctrl.nc ../input/gfs_ctrl.nc
(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d gfs_data.tile1.nc ../input/gfs_data.tile1.nc
(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d gfs_data.tile2.nc ../input/gfs_data.tile2.nc
(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d gfs_data.tile3.nc ../input/gfs_data.tile3.nc
(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d gfs_data.tile4.nc ../input/gfs_data.tile4.nc
n(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d gfs_data.tile5.nc ../input/gfs_data.tile5.nc
(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d  gfs_data.tile6.nc ../input/gfs_data.tile6.nc
(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d  sfc_data.tile1.nc ../input/sfc_data.tile1.nc
(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d sfc_data.tile2.nc ../input/sfc_data.tile2.nc
(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d sfc_data.tile3.nc ../input/sfc_data.tile3.nc
(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d sfc_data.tile4.nc ../input/sfc_data.tile4.nc
(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d sfc_data.tile5.nc ../input/sfc_data.tile5.nc
(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d sfc_data.tile6.nc ../input/sfc_data.tile6.nc
(base) [Ruiyu.Sun@hfe06 input.cactus]$ pwd
/scratch1/NCEPDEV/stmp2/Ruiyu.Sun/ROTDIRS/s2sw1/gfs.20210323/12/model_data/atmos/input.cactus
(base) [Ruiyu.Sun@hfe06 input.cactus]$

RUNDIRS input : SAME
Input.nml  comparison : same except for the locations of the fix files 
Ice_in : same

2024-08-13 19:26 UTC, RuiyuSun commented
> > I re-run the case on both Cactus and Hera. The one on Cactus failed and the one on Hera completed successfully. I compared ICs, restart files and some fix files, namelist variables specified in input.nml and ice_in. So far I haven't found any difference, except for the locations of some fix files given in the input.nml (expected).
> 
> details of the comparison:
> 
> Comparisons of restart files: Ice : same (base) [Ruiyu.Sun@hfe07 restart]$ nccmp -d 20210323.120000.cice_model.res.nc /scratch1/NCEPDEV/stmp2/Ruiyu.Sun/ROTDIRS/s2sw1/gdas.20210323/06/model_data/ice/restart/20210323.120000.cice_model.res.nc Wave : same (base) [Ruiyu.Sun@hfe06 restart]$ pwd /scratch1/NCEPDEV/stmp2/Ruiyu.Sun/ROTDIRS/s2sw1/gfs.20210323/06/model_data/wave/restart (base) [Ruiyu.Sun@hfe06 restart]$ cmp 20210323.120000.restart.uglo_100km 20210323.120000.restart.uglo_100km.cactus
> 
> Ocean: same (base) [Ruiyu.Sun@hfe07 restart]$ nccmp -d 20210323.120000.MOM.res.nc /scratch1/NCEPDEV/stmp2/Ruiyu.Sun/ROTDIRS/s2sw1/gdas.20210323/06/model_data/ocean/restart/20210323.120000.MOM.res.nc (base) [Ruiyu.Sun@hfe07 restart]$ pwd /scratch1/NCEPDEV/stmp2/Ruiyu.Sun/ROTDIRS/s2sw1/gdas.20210323.cactus.ocean.ice/06/model_data/ocean/restart
> 
> ATM ICs: same (base) [Ruiyu.Sun@hfe06 input.cactus]$ module load nccmp (base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d gfs_ctrl.nc ../input/gfs_ctrl.nc (base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d gfs_data.tile1.nc ../input/gfs_data.tile1.nc (base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d gfs_data.tile2.nc ../input/gfs_data.tile2.nc (base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d gfs_data.tile3.nc ../input/gfs_data.tile3.nc (base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d gfs_data.tile4.nc ../input/gfs_data.tile4.nc n(base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d gfs_data.tile5.nc ../input/gfs_data.tile5.nc (base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d gfs_data.tile6.nc ../input/gfs_data.tile6.nc (base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d sfc_data.tile1.nc ../input/sfc_data.tile1.nc (base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d sfc_data.tile2.nc ../input/sfc_data.tile2.nc (base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d sfc_data.tile3.nc ../input/sfc_data.tile3.nc (base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d sfc_data.tile4.nc ../input/sfc_data.tile4.nc (base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d sfc_data.tile5.nc ../input/sfc_data.tile5.nc (base) [Ruiyu.Sun@hfe06 input.cactus]$ nccmp -d sfc_data.tile6.nc ../input/sfc_data.tile6.nc (base) [Ruiyu.Sun@hfe06 input.cactus]$ pwd /scratch1/NCEPDEV/stmp2/Ruiyu.Sun/ROTDIRS/s2sw1/gfs.20210323/12/model_data/atmos/input.cactus (base) [Ruiyu.Sun@hfe06 input.cactus]$
> 
> RUNDIRS input : SAME Input.nml comparison : same except for the locations of the fix files Ice_in : same


The files in the fcst.* directory under the RUNDIRS were compared. All are the same except for **ice_diag.d.** . The ice_diag.d file is at /scratch1/NCEPDEV/stmp2/Ruiyu.Sun/rundir_comparison_hera_N_cactus/fcst.617494.**hera** and /scratch1/NCEPDEV/stmp2/Ruiyu.Sun/rundir_comparison_hera_N_cactus/fcst.243209.**cactus**. 

nccmp -d was used to compare the netcdf files. cmp was used to compare the biniary files and grb files

See below for details: 
The fcst rundirs from Hera test and cactus test are at /scratch1/NCEPDEV/stmp2/Ruiyu.Sun/rundir_comparison_hera_N_cactus
The following nc files are the same: 
aeroclim.m01.nc,
aeroclim.m02.nc,
aeroclim.m03.nc,
aeroclim.m04.nc,
aeroclim.m05.nc,
aeroclim.m06.nc,
aeroclim.m07.nc,
aeroclim.m08.nc,
aeroclim.m09.nc,
aeroclim.m10.nc,
aeroclim.m11.nc,
aeroclim.m12.nc,
atmf000.nc,
grid_cice_NEMS_mx500.nc,
kmtu_cice_NEMS_mx500.nc,
mesh.mx500.nc,
mesh.uglo_100km.nc,
Ugwp_limb_tau.nc,
All the txt files are the same: 
(base) [Ruiyu.Sun@hfe05 fcst.243209.cactus]$ ./diff_exe.sh
co2historicaldata_2009.txt,
co2historicaldata_2010.txt,
co2historicaldata_2011.txt,
co2historicaldata_2012.txt,
co2historicaldata_2013.txt,
co2historicaldata_2014.txt,
co2historicaldata_2015.txt,
co2historicaldata_2016.txt,
co2historicaldata_2017.txt,
co2historicaldata_2018.txt,
co2historicaldata_2019.txt,
co2historicaldata_2020.txt,
co2historicaldata_2021.txt,
co2historicaldata_2022.txt,
co2historicaldata_2023.txt,
co2historicaldata_2024.txt,
co2historicaldata_glob.txt,
co2monthlycyc.txt,
postxconfig-NT.txt,
postxconfig-NT_FH00.txt,
sfc_emissivity_idx.txt,
solarconstant_noaa_an.txt,
volcanic_aerosols_1850-1859.txt,
volcanic_aerosols_1860-1869.txt,
volcanic_aerosols_1870-1879.txt,
volcanic_aerosols_1880-1889.txt,
volcanic_aerosols_1890-1899.txt,
volcanic_aerosols_1900-1909.txt,
volcanic_aerosols_1910-1919.txt,
volcanic_aerosols_1920-1929.txt,
volcanic_aerosols_1930-1939.txt,
volcanic_aerosols_1940-1949.txt,
volcanic_aerosols_1950-1959.txt,
volcanic_aerosols_1960-1969.txt,
volcanic_aerosols_1970-1979.txt,
volcanic_aerosols_1980-1989.txt,
Volcanic_aerosols_1990-1999.txt,
Optics data files are the same: 
(base) [Ruiyu.Sun@hfe05 fcst.243209.cactus]$ ./optics_diff.sh
optics_BC.dat,
optics_DU.dat,
optics_OC.dat,
optics_SS.dat,
optics_SU.dat,
All the tables are the same: 
(base) [Ruiyu.Sun@hfe05 fcst.243209.cactus]$ ./tables_diff.sh
data_table,
diag_table,
diag_table_template,
field_table,
Noahmptable.tbl,
Aerosol data is the same: 
diff aerosol.dat ../fcst.617494.hera/
Thompson Binary data are the same:
(base) [Ruiyu.Sun@hfe05 fcst.243209.cactus]$ ./bincomp_exe.sh
freezeH2O.dat,
qr_acr_qgV2.dat,
qr_acr_qsV2.dat,


  CCN_ACTIVATE.BIN
Mod_def.ww3 is the same : 
cmp mod_def.ww3 ../fcst.617494.hera/mod_def.ww3
Ufs.configuration is the same: 
diff ufs.configure ../fcst.617494.hera/ufs.configure
Params_grib2_tbl_new is the same: 
diff  params_grib2_tbl_new ../fcst.617494.hera/
Ww3_shel.inp is the same: 
diff ww3_shel.inp ../fcst.617494.hera/
Model_configuration is the same : 
diff model_configure ../fcst.617494.hera/model_configure
H2o and o2 profiles are the same: 
cmp global_h2oprdlos.f77 ../fcst.617494.hera/global_h2oprdlos.f77
cmp global_o3prdlos.f77 ../fcst.617494.hera/global_o3prdlos.f77

input : SAME

Differences if file locations in the input.nml; need to compare them all: 
(base) [Ruiyu.Sun@hfe05 fcst.243209.cactus]$ diff input.nml ../fcst.617494.hera/
332,335c332,335
<   FNGLAC   = '/lfs/h2/emc/physics/noscrub/ruiyu.sun/git_GFSV17/global-workflow.20270809/fix/am/global_glacier.2x2.grb'
<   FNMXIC   = '/lfs/h2/emc/physics/noscrub/ruiyu.sun/git_GFSV17/global-workflow.20270809/fix/am/global_maxice.2x2.grb'
<   FNTSFC   = '/lfs/h2/emc/physics/noscrub/ruiyu.sun/git_GFSV17/global-workflow.20270809/fix/am/RTGSST.1982.2012.monthly.clim.grb'
<   FNSNOC   = '/lfs/h2/emc/physics/noscrub/ruiyu.sun/git_GFSV17/global-workflow.20270809/fix/am/global_snoclim.1.875.grb'
---
>   FNGLAC   = '/scratch1/NCEPDEV/global/Ruiyu.Sun/save/git/gfsv17_implementation/global-workflow.20270809/fix/am/global_glacier.2x2.grb'
>   FNMXIC   = '/scratch1/NCEPDEV/global/Ruiyu.Sun/save/git/gfsv17_implementation/global-workflow.20270809/fix/am/global_maxice.2x2.grb'
>   FNTSFC   = '/scratch1/NCEPDEV/global/Ruiyu.Sun/save/git/gfsv17_implementation/global-workflow.20270809/fix/am/RTGSST.1982.2012.monthly.clim.grb'
>   FNSNOC   = '/scratch1/NCEPDEV/global/Ruiyu.Sun/save/git/gfsv17_implementation/global-workflow.20270809/fix/am/global_snoclim.1.875.grb'
337,346c337,346
<   FNALBC   = '/lfs/h2/emc/physics/noscrub/ruiyu.sun/git_GFSV17/global-workflow.20270809/fix/orog/C48/sfc/C48.mx500.snowfree_albedo.tileX.nc'
<   FNALBC2  = '/lfs/h2/emc/physics/noscrub/ruiyu.sun/git_GFSV17/global-workflow.20270809/fix/orog/C48/sfc/C48.mx500.facsf.tileX.nc'
<   FNAISC   = '/lfs/h2/emc/physics/noscrub/ruiyu.sun/git_GFSV17/global-workflow.20270809/fix/am/IMS-NIC.blended.ice.monthly.clim.grb'
<   FNTG3C   = '/lfs/h2/emc/physics/noscrub/ruiyu.sun/git_GFSV17/global-workflow.20270809/fix/orog/C48/sfc/C48.mx500.substrate_temperature.tileX.nc'
<   FNVEGC   = '/lfs/h2/emc/physics/noscrub/ruiyu.sun/git_GFSV17/global-workflow.20270809/fix/orog/C48/sfc/C48.mx500.vegetation_greenness.tileX.nc'
<   FN [...]

2024-08-13 20:02 UTC, CatherineThomas-NOAA commented
Thanks @RuiyuSun!  Very detailed examination.

@NeilBarton-NOAA: Can you confirm that the ice_diag.d file is written as the model integrates and whether we should expect to see differences in this file on different machines?

2024-08-15 16:09 UTC, RuiyuSun commented
A solution forward is to use a smaller dt_inner for Thompson Microphysics scheme. The current dt_inner is 1200s, same as deltim. Two tests were successfully completed without warming with dt_inner=600s and 300s .

2024-08-15 17:57 UTC, RuiyuSun commented
The proposed change is to add a line (in B and I) in the config.fcst file.  

        if [[ "${sedi_semi}" == .true. ]]; then export dt_inner=${DELTIM} ; fi
        **_if [[ dt_inner -gt 300 ]]; then export  dt_inner=300; fi_**

2024-08-15 18:02 UTC, RuiyuSun commented
@junwang-noaa Please see above comment as we discussed at the global workflow meeting.

2024-08-20 16:22 UTC, RuiyuSun commented
> The proposed change is to add a line (in B and I) in the config.fcst file.
> 
> ```
>     if [[ "${sedi_semi}" == .true. ]]; then export dt_inner=${DELTIM} ; fi
>     **_if [[ dt_inner -gt 300 ]]; then export  dt_inner=300; fi_**
> ```

@XiaqiongZhou-NOAA Could you make the proposed change so that this can be tested? Thanks!!

2024-08-22 16:15 UTC, WalterKolczynski-NOAA commented
I think this is ready once it has been updated with current develop?

2024-08-22 16:20 UTC, XiaqiongZhou-NOAA commented
> I think this is ready once it has been updated with current develop?

updated to latest version.

2024-08-23 15:43 UTC, WalterKolczynski-NOAA requested changes

2024-08-23 15:43 UTC, WalterKolczynski-NOAA commented on parm/config/gefs/config.fcst
> +	if [[ dt_inner -gt 300 ]]; then export  dt_inner=300 ; fi
```suggestion
        if [[ dt_inner -gt 300 ]]; then export  dt_inner=300 ; fi
```

2024-08-23 15:43 UTC, WalterKolczynski-NOAA commented on parm/config/gfs/config.fcst
> +	if [[ dt_inner -gt 300 ]]; then export  dt_inner=300; fi
```suggestion
        if [[ dt_inner -gt 300 ]]; then export  dt_inner=300; fi
```

2024-08-23 15:44 UTC, WalterKolczynski-NOAA approved these changes

2024-08-23 15:57 UTC, merged