Correct ocean `MOM.res_#` stage copy
NOAA-EMC/global-workflow pull request #2868
Opened 2024-08-27 19:25 UTC by KateFriedman-NOAA

# Description

This PR corrects a bug in the staging job for ocean `MOM.res_#` IC files. The `OCNRES` value was coming in as an integer (e.g. `25`) but the `ocean.yaml.j2` file was checking for `"025"`. Correct to now set OCNRES to be three digits in staging script and also correct the for loop range to include third file.

Resolves #2864

# Type of change

- Bug fix (fixes something broken)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO

# How has this been tested?

Repeated the tests that the users who reported this ran.

2024-08-27 21:09 UTC, jswhit2 approved these changes

2024-08-27 22:46 UTC, RuiyuSun approved these changes

2024-08-28 01:38 UTC, WalterKolczynski-NOAA requested changes

2024-08-28 01:38 UTC, WalterKolczynski-NOAA commented on parm/stage/ocean.yaml.j2
> +        {% for nn in range(1, 3 + 1) %}
```suggestion
        {% for nn in range(1, 4) %}
```

2024-08-28 01:38 UTC, WalterKolczynski-NOAA commented on scripts/exglobal_stage_ic.py
> +            stage.task_config.OCNRES = f"{stage.task_config.OCNRES :03d}"
There's something unsettling about this. But fine for now.

2024-08-28 13:17 UTC, DavidHuber-NOAA approved these changes

2024-08-29 02:17 UTC, WalterKolczynski-NOAA approved these changes

2024-08-29 17:08 UTC, merged