Add capability of copying files from lustre to s3 bucket on AWS
NOAA-EMC/global-workflow pull request #2873
Opened 2024-08-28 17:16 UTC by weihuang-jedi

# Description

  Add capability to allow global-workflow copying file from lustre to s3 bucket on AWS, and other CSPs.

  Resolves #2872

# Type of change

- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? YES
- Does this change require an update to any of the following submodules? NO (If YES, please add a link to any PRs that are pending.)
  - [ ] EMC verif-global
  - [ ] GDAS
  - [ ] GFS-utils
  - [ ] GSI
  - [ ] GSI-monitor
  - [ ] GSI-utils
  - [ ] UFS-utils
  - [ ] UFS-weather-model
  - [ ] wxflow

# How has this been tested?

- Clone and build on AWS
- Run C48 Coupled C48 on AWS

# Checklist
- [ x] Any dependent changes have been merged and published
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ x] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

2024-08-29 16:10 UTC, weihuang-jedi commented
I understand that this PR is far from perfect.
But want to show a way that we can copy data from /lustre products to s3 bucket.
We want to see how other people think of this, and iterate to a better way.
Thanks,
Wei

2024-09-04 02:54 UTC, WalterKolczynski-NOAA commented
Unless there is need to populate the bucket right away, I think this is the wrong approach. It will be annoying to add and maintain, and also injects a bunch of unneeded code into production scripts.

Instead of adding a bunch of code to all of the jobs that write to COM as you've started here with products, we should do it at the end of the cycle, either by piggybacking on the existing archive job or creating a new job similar to the archive job that only runs on AWS. Then all the copying can be done in one go and in one place segregated from everything else.

2024-09-09 13:52 UTC, aerorahul requested changes
I agree with @WalterKolczynski-NOAA's assessment and review.

2024-09-17 15:01 UTC, weihuang-jedi commented
@WalterKolczynski-NOAA and @aerorahul,
I was thinking something similar to what Walter said, and only worried that will increase the total wall clock time of Global-Workflow, as if we make the copy work done at the archive stage.
The approach which I took here is an easy one to work, but as Walter said, make a lot of change to the current production code.
let me re-think about this request, and see if I can work out a way similar as archive.
Certainly, any suggestions/comments are more than welcome.

2024-09-25 15:23 UTC, TerrenceMcGuinness-NOAA commented on workflow/rocoto_viewer.py
We should never update this script in this fashion -- ever.
It is unsupported legacy code that happens to have some vestigial logic on EXPDIR.
These updates are speculative and irrelevant.

2024-09-25 15:31 UTC, weihuang-jedi commented on workflow/rocoto_viewer.py
That is a nice catch. I should not do any change here.
I will remove those, even this PR is not going any where.

2024-09-25 15:51 UTC, TerrenceMcGuinness-NOAA commented on workflow/rocoto_viewer.py
Thanks Wei.

2024-09-25 15:51 UTC, TerrenceMcGuinness-NOAA commented on workflow/rocoto_viewer.py
Right, Just wanted to keep you up to speed.

2024-10-04 11:59 UTC, DavidHuber-NOAA commented
Opened issue https://github.com/NOAA-EMC/wxflow/issues/42 to add bucket transfer capability to wxflow.

2024-11-12 19:18 UTC, aerorahul commented
Closing after consulting w/ @weihuang-jedi 
This capability will be coordinated in a future sprint.

2024-11-12 19:18 UTC, closed without merging