Move to contrib installation of spack-stack on Jet
NOAA-EMC/global-workflow pull request #2878
Opened 2024-08-29 20:44 UTC by InnocentSouopgui-NOAA

# Description
Migrates Global Workflow to use contrib installation of spack-stack  on Jet.
Following the failure of the storage /lfs4 on Jet, the installation of spack spack moved to /contrib.
All softwares relying on spack-stack on Jet needs update.

  Resolves #2841 
  Refs NOAA-EMC/gfs-utils#78
  Refs NOAA-EMC/GSI#786
  Refs NOAA-EMC/GSI-Monitor#143
  Refs NOAA-EMC/GSI-utils#51
  Refs ufs-community/UFS_UTILS#977

# Type of change
- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? YES/NO (If YES, please add a link to any PRs that are pending.)
  - [ ] EMC verif-global
  - [ ] GDAS
  - [X] GFS-utils NOAA-EMC/gfs-utils#79
  - [X] GSI NOAA-EMC/GSI#787
  - [X] GSI-monitor NOAA-EMC/GSI-Monitor#144
  - [X] GSI-utils NOAA-EMC/GSI-utils#52
  - [X] UFS-utils ufs-community/UFS_UTILS#978
  - [ ] UFS-weather-model
  - [ ] wxflow

# How has this been tested?
Example:
- Clone and build on Jet
- Cycled experiments (48+ hours) at resolutions
  - [ ] 96/48 on kjet
  - [ ] 192/96 on kjet
  - [ ] 384/192 on kjet

- Forecast only experiment (48+ hours) at resolutions
  - [ ] 48
  - [ ] 96
  - [ ] 192
  - [ ] 384

# Checklist
- [ ] Any dependent changes have been merged and published
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] New and existing tests pass with my changes
- [X] I have made corresponding changes to the documentation if necessary

2024-09-03 19:07 UTC, InnocentSouopgui-NOAA commented
I am getting errors of the form bellow in forecast steps (tasks gdasfcst_seg0 and all enkfgdasfcst_mem###)
That is while running C192/C96 on Jet. It happened from the very first cycle, so it did not complete a single cycle.

@DavidHuber-NOAA 

```
21: Warn_K=   6 (i,j)=   87   12 (lon,lat)=123.209 -43.765 VA = 264.64157
21:      K=   5    338.73022
21:      K=   7    217.40834
21: Warn_K=   6 (i,j)=   88   13 (lon,lat)=121.423 -43.705 VA = 250.69765
21:      K=   5    297.46832
21:      K=   7    213.49741
21: Warn_K=   6 (i,j)=   84   16 (lon,lat)=122.124 -46.976 VA = 251.07759
21:      K=   5    256.00562
21:      K=   7    241.60887
 0: PASS: fcstRUN phase 2, n_atmsteps =               27 time is         1.264142
 5:
 5: FATAL from PE     5: NaN in input field of mpp_reproducing_sum(_2d), this indicates numerical instability
 5:
13:
13: FATAL from PE    13: NaN in input field of mpp_reproducing_sum(_2d), this indicates numerical instability
13:
21:
21: FATAL from PE    21: NaN in input field of mpp_reproducing_sum(_2d), this indicates numerical instability
21:
13: Image              PC                Routine            Line        Source
13: ufs_model.x        00000000086C51A7  Unknown               Unknown  Unknown
13: ufs_model.x        00000000078AD1B9  mpp_mod_mp_mpp_er          72  mpp_util_mpi.inc
13: ufs_model.x        0000000007B61AB6  mpp_efp_mod_mp_mp         195  mpp_efp.F90
13: ufs_model.x        0000000007AB2D99  mpp_domains_mod_m         143  mpp_global_sum.fh
13: ufs_model.x        0000000003E9EB6A  fv_grid_utils_mod        3077  fv_grid_utils.F90
13: ufs_model.x        0000000003F2ED3E  fv_mapz_mod_mp_la         794  fv_mapz.F90
13: libiomp5.so        0000146B48A6CBB3  __kmp_invoke_micr     Unknown  Unknown
13: libiomp5.so        0000146B489E8FAC  __kmp_fork_call       Unknown  Unknown
13: libiomp5.so        0000146B489AACB5  __kmpc_fork_call      Unknown  Unknown
13: ufs_model.x        0000000003F2A129  fv_mapz_mod_mp_la         683  fv_mapz.F90
13: ufs_model.x        0000000003E2EE61  fv_dynamics_mod_m         771  fv_dynamics.F90
13: ufs_model.x        0000000003C9236C  atmosphere_mod_mp         688  atmosphere.F90
13: ufs_model.x        0000000003A3490D  atmos_model_mod_m         879  atmos_model.F90
13: ufs_model.x        00000000035F688C  module_fcst_grid_        1335  module_fcst_grid_comp.F90
```

2024-09-05 15:30 UTC, InnocentSouopgui-NOAA commented
It seems to be just a bad day

2024-09-05 19:55 UTC, InnocentSouopgui-NOAA commented
I build initial conditions for other days and it cycled smoothly.

2024-09-06 12:50 UTC, RussTreadon-NOAA commented
GSI PR [#787](https://github.com/NOAA-EMC/GSI/pull/787) has been merged into GSI `develop`.  Done at [`9f44c87`](https://github.com/NOAA-EMC/GSI/commit/9f44c8798c2087aca06df8f629699632e57df431).

The `sorc/gsi_enkf.fd` hash in `InnocentSouopgui-NOAA:migration-jet-contrib` must be updated to [`9f44c87`](https://github.com/NOAA-EMC/GSI/commit/9f44c8798c2087aca06df8f629699632e57df431) to bring these changes into g-w.

2024-09-10 13:06 UTC, InnocentSouopgui-NOAA commented
A check is failing with the following message,
```
fatal: Fetched in submodule path 'ufs_utils.fd', but it did not contain 0426bf793051530794ec8f182e04f5cf129d0a90. Direct fetching of that commit failed.
```
How to diagnose what is going on?

2024-09-10 13:12 UTC, DavidHuber-NOAA commented
@InnocentSouopgui-NOAA I suspect that the hash you are pointing to is for your own branch.  Update the hash instead to https://github.com/ufs-community/UFS_UTILS/commit/06eec5b6f636123835e2dfd9fc5229980c006735.

2024-09-10 14:22 UTC, InnocentSouopgui-NOAA commented
> @InnocentSouopgui-NOAA I suspect that the hash you are pointing to is for your own branch. Update the hash instead to [ufs-community/UFS_UTILS@06eec5b](https://github.com/ufs-community/UFS_UTILS/commit/06eec5b6f636123835e2dfd9fc5229980c006735).

Thanks @DavidHuber-NOAA , that was the issue.

2024-09-10 16:09 UTC, DavidHuber-NOAA commented
@InnocentSouopgui-NOAA Just a heads up, there is a bug in the newest GSI-utils that will cause the gdasanalcalc job to fail when performing GDASApp analyses (i.e. the `C96C48_ufs_hybatmDA` CI test) as noted in https://github.com/NOAA-EMC/global-workflow/pull/2819#issuecomment-2340706398.

2024-09-10 17:01 UTC, InnocentSouopgui-NOAA commented
@DavidHuber-NOAA , should delay this PR for that bug?
I updated all the hash, I am doing a final test at res C96/48 before getting this out for review.

2024-09-10 17:57 UTC, DavidHuber-NOAA commented
I think a delay would be preferred, unfortunately, as this will break development for GDASApp.  That said, I think we can go ahead and review it.

2024-09-10 18:01 UTC, InnocentSouopgui-NOAA commented
Everything is ready for review.

2024-09-13 19:04 UTC, WalterKolczynski-NOAA requested changes

2024-09-13 19:04 UTC, WalterKolczynski-NOAA commented on ush/forecast_predet.sh
> +#  fi
Please remove this commented code.

2024-09-13 19:04 UTC, WalterKolczynski-NOAA commented on sorc/gdas.cd
Please check your GDAS App version. I think this is an earlier version than the one in develop.

2024-09-16 13:16 UTC, InnocentSouopgui-NOAA commented on sorc/gdas.cd
That is true. there was no change in GDAS and I did think about updating its hash.
I believe GDAS is not supported on Jet yet.  However, If needed I can update it to the latest in the develop branch.
Let me know.
Let me tag @DavidHuber-NOAA @KateFriedman-NOAA for comments on the support of GDAS App on Jet.

2024-09-16 13:24 UTC, DavidHuber-NOAA commented on sorc/gdas.cd
@InnocentSouopgui-NOAA You are correct, the GDASApp is not supported on Jet at this time.  However, this isn't the issue that Walter is raising.  The hash of the GDASApp that you have in `migration-jet-contrib` is older that the hash that is in the global-workflow develop branch.  Can you update your `GDASApp` branch?

```bash
cd global-workflow/sorc/gdas.cd
git checkout faa95efb18f0
cd ../
git add gdas.cd
git commit
git push
```

2024-09-16 13:54 UTC, InnocentSouopgui-NOAA commented on ush/forecast_predet.sh
> +#  fi
Done.

2024-09-16 14:03 UTC, InnocentSouopgui-NOAA commented on sorc/gdas.cd
Done.

2024-09-17 18:34 UTC, WalterKolczynski-NOAA approved these changes, later dismissed

2024-09-17 18:36 UTC, DavidHuber-NOAA commented
@InnocentSouopgui-NOAA The gsi-utils bug has been fixed.  You should be able to update the hash now.

2024-09-17 18:41 UTC, KateFriedman-NOAA approved these changes, later dismissed
Updates look good, thanks @InnocentSouopgui-NOAA ! FYI I am updating the obsproc, prepobs and fit2obs versions in PR #2903 so those external pieces will be taken care of by the time this goes in.

2024-09-19 16:11 UTC, DavidHuber-NOAA requested changes

2024-09-19 16:11 UTC, DavidHuber-NOAA commented on sorc/gsi_utils.fd
@InnocentSouopgui-NOAA Can you please update this to the following hash: https://github.com/NOAA-EMC/GSI-utils/commit/a6ea311e5c82369d255e3afdc99c1bce0c9a3014?  This fixes an issue when running JEDI-based analyses.

2024-09-19 17:21 UTC, InnocentSouopgui-NOAA commented on sorc/gsi_utils.fd
Done.

2024-09-19 17:26 UTC, DavidHuber-NOAA submitted a review, later dismissed
Changes look good.  Thanks for the work @InnocentSouopgui-NOAA!

2024-09-23 13:30 UTC, WalterKolczynski-NOAA approved these changes, later dismissed

2024-09-23 14:32 UTC, KateFriedman-NOAA submitted a review, later dismissed
Thanks @InnocentSouopgui-NOAA !

2024-09-24 13:20 UTC, KateFriedman-NOAA submitted a review, later dismissed
Updates look good, thanks @InnocentSouopgui-NOAA !

2024-09-24 13:23 UTC, DavidHuber-NOAA submitted a review, later dismissed

2024-09-26 12:57 UTC, InnocentSouopgui-NOAA commented
@KateFriedman-NOAA , @DavidHuber-NOAA 
The automated tests failed on wcoss2. 
Can you have a look to investigate further? The error says "CPU oversubscription detected for application".
I do not have access to wcoss2 to check what is going on.

2024-09-26 13:04 UTC, KateFriedman-NOAA commented
> @KateFriedman-NOAA , @DavidHuber-NOAA The automated tests failed on wcoss2. Can you have a look to investigate further? The error says "CPU oversubscription detected for application". I do not have access to wcoss2 to check what is going on.

That looks like a similar problem that cropped up in PR #2895 and which @DavidHuber-NOAA had that PR include updates to the prep job resources to resolve it on WCOSS2. Sync your PR branch with g-w `develop` and we'll retry the WCOSS2 CI again with those updated prep job resources.

2024-09-26 13:19 UTC, InnocentSouopgui-NOAA commented
> > @KateFriedman-NOAA , @DavidHuber-NOAA The automated tests failed on wcoss2. Can you have a look to investigate further? The error says "CPU oversubscription detected for application". I do not have access to wcoss2 to check what is going on.
> 
> That looks like a similar problem that cropped up in PR #2895 and which @DavidHuber-NOAA had that PR include updates to the prep job resources to resolve it on WCOSS2. Sync your PR branch with g-w `develop` and we'll retry the WCOSS2 CI again with those updated prep job resources.

I just updated my branch.

2024-09-27 13:41 UTC, InnocentSouopgui-NOAA commented
@KateFriedman-NOAA , @DavidHuber-NOAA 

WCOSS2 has a disk space issue.

**Disk quota exceeded** in `gfsfcst_seg0.log`
**FATAL ERROR: write error** in `gfsatmos_prod_f###.log`

2024-09-27 14:02 UTC, KateFriedman-NOAA commented
Hmmmmmm the stmp quota on WCOSS2-Cactus is currently at 66%. It's possible it hit 100% and then fell overnight because of the scrubber. We'd need to retry the CI test again.

2024-09-30 16:40 UTC, WalterKolczynski-NOAA approved these changes

2024-09-30 16:41 UTC, merged