Support gefs C48 on Azure
NOAA-EMC/global-workflow pull request #2881
Opened 2024-08-30 15:15 UTC by weihuang-jedi

# Description

# Type of change

- Bug fix (fixes something broken)
- New feature (adds functionality)
- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? YES/NO
- Does this change require a documentation update? YES/NO
- Does this change require an update to any of the following submodules? YES/NO (If YES, please add a link to any PRs that are pending.)
  - [ ] EMC verif-global
  - [ ] GDAS
  - [ ] GFS-utils
  - [ ] GSI
  - [ ] GSI-monitor
  - [ ] GSI-utils
  - [ ] UFS-utils
  - [ ] UFS-weather-model
  - [ ] wxflow

# How has this been tested?

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] I have made corresponding changes to the documentation if necessary

2024-08-30 21:28 UTC, aerorahul requested changes
everything except 1 thing looks good.

2024-08-30 21:28 UTC, aerorahul commented on env/AZUREPW.env
> +    export APRUN="${launcher} -n ${ntasks}"
Do not export this variable here.  It should only be exported for a specific task.

2024-09-03 20:03 UTC, aerorahul commented on env/AZUREPW.env
> +    export APRUN="${launcher} -n ${ntasks}"
```suggestion
   APRUN="${launcher} -n ${ntasks}"
```
do not export `APRUN` here.

2024-09-10 14:25 UTC, aerorahul submitted a review, later dismissed
looks good

2024-09-10 14:27 UTC, aerorahul commented
@weihuang-jedi The PR looks good, but it appears has some conflicts.  If you resolve these, we will merge this.

2024-09-13 19:05 UTC, WalterKolczynski-NOAA approved these changes

2024-09-13 19:10 UTC, aerorahul approved these changes
looks good.

2024-09-13 19:39 UTC, merged