Enable parallel metp jobs and fix race condition with the gfscleanup job
NOAA-EMC/global-workflow pull request #2907
Opened 2024-09-12 12:40 UTC by DavidHuber-NOAA

# Description
This brings in a change to EMC_verif-global that offsets the start time of parallel instances when running metp jobs.  This prevents Python from attempting to create the same directory in multiple instances.
Simultaneously, this also fixes an issue with the `gfscleanup` job potentially running before the `metp` jobs.
Resolves #2906
Resolves #2899 

# Type of change
- New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? YES (If YES, please add a link to any PRs that are pending.)
  - [x] EMC verif-global PR https://github.com/NOAA-EMC/EMC_verif-global/pull/135
  - [ ] GDAS
  - [ ] GFS-utils
  - [ ] GSI
  - [ ] GSI-monitor
  - [ ] GSI-utils
  - [ ] UFS-utils
  - [ ] UFS-weather-model
  - [ ] wxflow

# How has this been tested?
Standalone test on Orion with 40 parallel instances over a 30-cycle span.

# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes

2024-09-12 12:43 UTC, malloryprow approved these changes

2024-09-12 19:05 UTC, DavidHuber-NOAA commented
I added a one-line fix to `enkf.yaml.j2` that @AntonMFernando-NOAA found.  This code has not been used as the `eomg` jobs are not runnable at this time, but it will help when others try to use code samples.

2024-09-16 13:02 UTC, DavidHuber-NOAA commented
I finished running tests on Hera.  All metp jobs passed.  Marking this PR as ready for review.

2024-09-17 19:49 UTC, WalterKolczynski-NOAA requested changes

2024-09-17 19:49 UTC, WalterKolczynski-NOAA commented on workflow/rocoto/gfs_tasks.py
> +            if self.app_config.do_metp:
```suggestion
        if self.app_config.do_metp and self.run in ['gfs']:
```

2024-09-23 13:47 UTC, WalterKolczynski-NOAA approved these changes

2024-09-27 04:23 UTC, merged