Add CODEOWNERS
NOAA-EMC/global-workflow pull request #2996
Opened 2024-10-09 20:04 UTC by aerorahul

# Description
This PR:
- adds a `CODEOWNERS` file to the repository.  global-workflow is a collaborative space where contributions come from a variety of sources. This file will ensure that new development gets reviewed by the appropriate SME.

# Type of change
- [X] New feature (adds functionality)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? NO
  - [ ] EMC verif-global 
  - [ ] GDAS 
  - [ ] GFS-utils 
  - [ ] GSI 
  - [ ] GSI-monitor 
  - [ ] GSI-utils 
  - [ ] UFS-utils 
  - [ ] UFS-weather-model 
  - [ ] wxflow 

# How has this been tested?
There is no code change associated with this PR

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my code, including function, input, and output descriptions
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] This change is covered by an existing CI test or a new one has been added
- [ ] I have made corresponding changes to the system documentation if necessary

2024-10-10 13:44 UTC, KateFriedman-NOAA reviewed
Looks good, thanks for adding this @aerorahul ! Left a few comments.

2024-10-10 13:44 UTC, KateFriedman-NOAA commented on .github/CODEOWNERS
> +# This file is ensure that new development gets reviewed by the appropriate SME
```suggestion
# This file is to ensure that new development gets reviewed by the appropriate SME
```

2024-10-10 13:44 UTC, KateFriedman-NOAA commented on .github/CODEOWNERS
> +jobs/JGDAS_FIT2OBS
Jack Woolen for `jobs/JGDAS_FIT2OBS`?

2024-10-10 13:44 UTC, KateFriedman-NOAA commented on .github/CODEOWNERS
> +jobs/JGFS_ATMOS_CYCLONE_TRACKER
Jiayi for the CYCLONE and FSU_GENESIS job scripts?

2024-10-10 14:01 UTC, DavidHuber-NOAA requested changes

2024-10-10 14:01 UTC, DavidHuber-NOAA commented on .github/CODEOWNERS
> +jobs/JGLOBAL_ARCHIVE
```suggestion
jobs/JGLOBAL_ARCHIVE @DavidHuber-NOAA
```

2024-10-10 14:01 UTC, DavidHuber-NOAA commented on .github/CODEOWNERS
> +tropcy_relocate_extrkr.sh
Jiayi?

2024-10-10 14:01 UTC, DavidHuber-NOAA commented on .github/CODEOWNERS
> +ush/python/pygfs/task/aero_prepobs.py
Cory, David New?

2024-10-11 14:05 UTC, aerorahul commented on .github/CODEOWNERS
> +jobs/JGDAS_FIT2OBS
```suggestion
jobs/JGDAS_FIT2OBS @jack-woollen 
```

2024-10-11 14:05 UTC, aerorahul commented on .github/CODEOWNERS
> +jobs/JGFS_ATMOS_CYCLONE_TRACKER
```suggestion
jobs/JGFS_ATMOS_CYCLONE_GENESIS @JiayiPeng-NOAA 
jobs/JGFS_ATMOS_CYCLONE_TRACKER @JiayiPeng-NOAA 
```

2024-10-11 14:06 UTC, aerorahul commented on .github/CODEOWNERS
> +tropcy_relocate_extrkr.sh
```suggestion
syndat_getjtbul.sh @JiayiPeng-NOAA 
syndat_qctropcy.sh @JiayiPeng-NOAA 
tropcy_relocate.sh @JiayiPeng-NOAA 
tropcy_relocate_extrkr.sh @JiayiPeng-NOAA 
```

2024-10-11 14:07 UTC, aerorahul commented on .github/CODEOWNERS
> +ush/python/pygfs/task/aero_prepobs.py
```suggestion
ush/python/pygfs/task/aero_prepobs.py @CoryMartin-NOAA 
```

2024-10-11 14:07 UTC, aerorahul commented on .github/CODEOWNERS
> +ush/python/pygfs/utils/marine_da_utils.py @guillaumevernieres @AndrewEichmann-NOAA
```suggestion
ush/python/pygfs/utils/marine_da_utils.py @guillaumevernieres @AndrewEichmann-NOAA

```

2024-10-11 14:20 UTC, DavidHuber-NOAA approved these changes

2024-10-11 15:23 UTC, KateFriedman-NOAA approved these changes
Looks good, thanks for putting this together @aerorahul !

2024-10-17 20:02 UTC, WalterKolczynski-NOAA approved these changes

2024-10-17 20:04 UTC, merged