Update JGDAS ENKF ECEN job
NOAA-EMC/global-workflow pull request #3050
Opened 2024-10-31 16:04 UTC by mingshichen-noaa

# Description
 
NCO has requested that each COM variable specify whether it is an input or an output. This completes that process for the global jgdas enkf ecen job.

Refs https://github.com/NOAA-EMC/global-workflow/issues/2451

# Type of change

- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
 
- Clone and build on RDHPCS
- Cycled tests on Hercules
- Forecast-only tests on Hercules
 
# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessary

2024-10-31 16:43 UTC, CoryMartin-NOAA reviewed
Why are there no changes for `COM_ATMOS_ANALYSIS_STAT`?

2024-10-31 16:58 UTC, KateFriedman-NOAA reviewed
I second @CoryMartin-NOAA 's comment. Changes in this PR look good so far but there are other `COM` variables in `scripts/exgdas_enkf_ecen.sh` that also need to be updated to their `COMIN`/`COMOUT` versions. Please update those variables as well, thanks!

2024-10-31 19:10 UTC, mingshichen-noaa commented
@CoryMartin-NOAA @KateFriedman-NOAA 
Hi both,
I am sorry to have missed git  push. Right now I have made updating.

2024-11-01 13:45 UTC, KateFriedman-NOAA commented
> I am sorry to have missed git push. Right now I have made updating.

@mingshichen-noaa Thanks for committing those additional updates. Question, the testing you did included these `COM` changes that you just pushed?

2024-11-01 15:23 UTC, mingshichen-noaa commented
Kate,
Yes, testing and git push were done yesterday.

2024-11-01 16:42 UTC, KateFriedman-NOAA requested changes

2024-11-01 16:42 UTC, KateFriedman-NOAA commented on scripts/exgdas_enkf_ecen.sh
>     fi
Also please double check lines 179 and 181. I think they should also be `COMOUT_*`. Thanks!

2024-11-01 16:42 UTC, KateFriedman-NOAA commented on scripts/exgdas_enkf_ecen.sh
> +      ${NLN} "${COMIN_ATMOS_ANALYSIS_STAT}/${APREFIX_ENS}atma00${FHR}.ensmean.nc" "./atmanl_ensmean"
I think lines 159 and 161 should be `COMOUT_*`. Please double check, thanks!

2024-11-01 16:42 UTC, KateFriedman-NOAA commented on jobs/JGDAS_ENKF_ECEN
> +  COMIN_ATMOS_ANALYSIS_STAT:COM_ATMOS_ANALYSIS_TMPL
See my comments in the other script. I think this should be `COMOUT_ATMOS_ANALYSIS_STAT`. Please double check, thanks!

2024-11-01 20:33 UTC, CoryMartin-NOAA commented
I agree with @KateFriedman-NOAA those are links to files produced by executables and thus should be COMOUT

2024-11-01 22:41 UTC, mingshichen-noaa commented
Kate,
I agree with your comments and suggestions. I have made change and done git add/commit/push them.

2024-11-04 12:37 UTC, KateFriedman-NOAA approved these changes
I think the changes are correct now. Approve pending successful completion of CI tests and approval by other reviewers.

2024-11-04 13:30 UTC, CoryMartin-NOAA approved these changes

2024-11-04 19:23 UTC, WalterKolczynski-NOAA approved these changes

2024-11-05 14:31 UTC, DavidHuber-NOAA approved these changes

2024-11-09 02:36 UTC, merged