Update JGDAS_ENKF_SFC and JGDAS_ENKF_UPDATE jobs with COMIN/COMOUT instead of COM
NOAA-EMC/global-workflow pull request #3170
Opened 2024-12-16 16:50 UTC by mingshichen-noaa

# Description
 
NCO has requested that each COM variable specify whether it is an input or an output. This completes that process for the global  JGDAS_ENKF_SFC and JGDAS_ENKF_UPDATE jobs.

Refs https://github.com/NOAA-EMC/global-workflow/issues/2451

# Type of change

- Maintenance (code refactor, clean-up, new CI test, etc.)

# Change characteristics
- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO

# How has this been tested?
 
- Clone and build on RDHPCS
- Cycled tests on Hercules
- Forecast-only tests on Hercules
 
# Checklist
- [x] Any dependent changes have been merged and published
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing tests pass with my changes
- [x] I have made corresponding changes to the documentation if necessar

2024-12-16 21:03 UTC, KateFriedman-NOAA commented
@mingshichen-noaa FYI, please ignore CI test messages in your PR. We are using your PR to test a new CI setup on WCOSS2. We will rerun the CI tests for this PR once reviews have completed. Thanks!

2024-12-16 21:44 UTC, KateFriedman-NOAA commented
CI Tests set up to run in /lfs/h2/emc/ptmp/emc.global/PR/PR_3170/RUNTESTS on WCOSS

2024-12-16 22:04 UTC, mingshichen-noaa commented
@KateFriedman-NOAA 
I stopped CI test on Hercules.

2024-12-17 14:22 UTC, KateFriedman-NOAA commented
> I stopped CI test on Hercules.

@mingshichen-noaa CI tests that you were running under your account? Why did you stop them? Was there an error?

2024-12-17 14:44 UTC, mingshichen-noaa commented
> > I stopped CI test on Hercules.
> 
> @mingshichen-noaa CI tests that you were running under your account? Why did you stop them? Was there an error?

2024-12-17 14:50 UTC, mingshichen-noaa commented
@KateFriedman-NOAA 
After I checked the running status with rocotostat and found all running states with SUCCEEDED in cycle from 202112201800 to 202112210600, I stopped the crontab running.

2024-12-17 14:52 UTC, mingshichen-noaa commented
@KateFriedman-NOAA 
My running results are located at /work2/noaa/global/mchen/test/jobs/JGDAS_ENKF_SFC/EXPDIR/C96C48_hybatmDA.

2024-12-17 14:53 UTC, KateFriedman-NOAA commented
@mingshichen-noaa Glad to hear your tests on Hercules succeeded. Please leave this PR open until it's merged or the code managers decide to close. Thanks!

2025-01-06 15:26 UTC, mingshichen-noaa commented
@WalterKolczynski-NOAA 
How about CI-Wcoss2-Running on PR (#3170)?

2025-01-08 05:54 UTC, WalterKolczynski-NOAA requested changes

2025-01-08 05:54 UTC, WalterKolczynski-NOAA commented on scripts/exgdas_enkf_update.sh
> +cat stdout stderr > "${COMIN_ATMOS_ANALYSIS_STAT}/${ENKFSTAT}"
This is clearly an output. It's possible COM_ATMOS_ANALYSIS is both an IN and an OUT for this job. Please evaluate what the script is doing carefully to determine what are inputs and what are outputs.

2025-01-08 05:54 UTC, WalterKolczynski-NOAA commented on jobs/JGDAS_ENKF_UPDATE
> +   "${DBNROOT}/bin/dbn_alert" "MODEL" "ENKF1_MSC_enkfstat" "${job}" "${COMIN_ATMOS_ANALYSIS_STAT}/${APREFIX}enkfstat"
This notification should be about an output too.

2025-01-08 16:42 UTC, KateFriedman-NOAA commented on scripts/exgdas_enkf_update.sh
> +cat stdout stderr > "${COMIN_ATMOS_ANALYSIS_STAT}/${ENKFSTAT}"
I second Walter's comment. It appears that `COM_ATMOS_ANALYSIS` is both an IN and an OUT for this job. Please examine and if you agree, please define the variable twice, once as an IN and once as an OUT. Then update the script to use the appropriate IN or OUT version of the variable. Thanks!

2025-01-08 16:44 UTC, KateFriedman-NOAA commented on jobs/JGDAS_ENKF_UPDATE
> +   "${DBNROOT}/bin/dbn_alert" "MODEL" "ENKF1_MSC_enkfstat" "${job}" "${COMIN_ATMOS_ANALYSIS_STAT}/${APREFIX}enkfstat"
I agree with Walter's comment. This should be a `COMOUT` variable here since it's reporting the existence of an output file via `dbn_alert`.

2025-01-08 17:35 UTC, mingshichen-noaa commented on jobs/JGDAS_ENKF_UPDATE
> +   "${DBNROOT}/bin/dbn_alert" "MODEL" "ENKF1_MSC_enkfstat" "${job}" "${COMIN_ATMOS_ANALYSIS_STAT}/${APREFIX}enkfstat"
@WalterKolczynski-NOAA @KateFriedman-NOAA 
Yes, I agree with your comments. I am working on the modifications.

2025-01-08 20:36 UTC, mingshichen-noaa commented
@WalterKolczynski-NOAA @KateFriedman-NOAA 
I have modified jobs/JGDAS_ENKF_UPDATE and scripts/exgdas_enkf_update.sh and git add/commit/push the modified files.
I am building the modified PR and then do the CI PR test in Hercules.

2025-01-09 20:02 UTC, mingshichen-noaa commented
@WalterKolczynski-NOAA,  @KateFriedman-NOAA 
After I made modification on jobs/JGDAS_ENKF_UPDATE and scripts/exgdas_enkf_update.sh, I did PR tests in local repository in Hercules. The results show most of tasks were run successfully except task ( gdas_atmanlupp & gfs_fcst_seg0) failed to run.
Besides, above-mentioned CI Unit Tests / Run unit tests on CI system (pull_request) showed failed info:
fatal: remote error: upload-pack: not our ref f0a1649115882e3446c896ebe7efa7e0778d6840
fatal: Fetched in submodule path 'ufs_model.fd', but it did not contain f0a1649115882e3446c896ebe7efa7e0778d6840. Direct fetching of that commit failed.
Error: Process completed with exit code 128.
Could you give me advice to handle the failure? Thank you in advance.

2025-01-14 16:33 UTC, WalterKolczynski-NOAA commented
This PR should not be updating any submodules.

2025-01-14 17:25 UTC, mingshichen-noaa commented
@WalterKolczynski-NOAA

2025-01-14 19:02 UTC, mingshichen-noaa commented
@WalterKolczynski-NOAA 
In order to resolve the above-mentioned conflicting files: sorc/gdas.cd   sorc/gfs_utils.fd,  I remembered you ever told me the following resolved method:
"you should have run git submodule update --init --recursive to update the submodules locally. Now, you need to check out the correct versions from develop and commit them (or rebase interactively to remove the offending commits, but that is a bit advanced). "
I forgot how to get the correct versions of the two directories from develop. Will you be available tomorrow to make google chat?

2025-01-16 18:59 UTC, WalterKolczynski-NOAA commented
@mingshichen-noaa For each submodule you've inadvertently modified:

1. Look up the correct [hash from develop](https://github.com/NOAA-EMC/global-workflow/tree/develop/sorc)
2. 
```
cd sorc/<submodule>
git checkout <hash>
cd ..
git add <submodule>
# repeat for all submodules
git commit
```

2025-01-16 21:15 UTC, WalterKolczynski-NOAA commented
This is still not the correct hash for ufs_model:

![image](https://github.com/user-attachments/assets/11b29055-fcfc-49fc-a390-cc02a2dc2ee1)
![image](https://github.com/user-attachments/assets/a87ed75f-fddb-4cab-a802-f0eea01bc2ba)

2025-01-23 17:57 UTC, WalterKolczynski-NOAA commented
@mingshichen-noaa There haven't been any updates to this PR in a week. Some submodule hashes are still incorrect. This should have been a pretty quick fix. What's the hold-up?

2025-01-23 21:36 UTC, mingshichen-noaa commented
@KateFriedman-NOAA 
On Tuesday Rahul made a google chat with me to figure out the issue but not done. These days I have tried to figure out submodule issues in PR (#3170), based on your suggestion and Kate's instruction and some solution suggestions from google. Right now I am taking CI test in Hercules. I expect to resolve the issue as soon as possible.

2025-01-27 18:44 UTC, closed without merging