Enable bias correction for aerosol DA
NOAA-EMC/global-workflow pull request #3189
Opened 2024-12-20 21:50 UTC by ypwang19

# Description
This PR enables the capability of bias correction for aerosol DA in the workflow.

- Is this a breaking change (a change in existing functionality)? NO
- Does this change require a documentation update? NO
- Does this change require an update to any of the following submodules? YES (If YES, please add a link to any PRs that are pending.)
  - [ ] GDAS 
  - [ ] jcd-gdas 

# How has this been tested?
- Cycled test on Hera

# Checklist
- [ ] Any dependent changes have been merged and published
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my code, including function, input, and output descriptions
- [ ] My changes generate no new warnings
- [ ] New and existing tests pass with my changes
- [ ] This change is covered by an existing CI test or a new one has been added
- [ ] Any new scripts have been added to the .github/CODEOWNERS file with owners
- [ ] I have made corresponding changes to the system documentation if necessary

2024-12-23 18:31 UTC, RussTreadon-NOAA commented
@ypwang19:  Do we have PRs in GDASApp and jcb-gdas for the changes required by this PR?  If _yes_, we should cite these PRs in this g-w PR.  Then the g-w team and others can see when the prerequisite PRs are merged.

2024-12-23 18:52 UTC, ypwang19 commented
> @ypwang19: Do we have PRs in GDASApp and jcb-gdas for the changes required by this PR? If _yes_, we should cite these PRs in this g-w PR. Then the g-w team and others can see when the prerequisite PRs are merged.

Yes, we have. I am going to open PRs in GDASApp and jcb-gdas soon and will cite them here.

2025-01-03 16:01 UTC, RussTreadon-NOAA commented
@ypwang19 , now that 
- GDAS https://github.com/NOAA-EMC/GDASApp/pull/1426
-  jcb-gdas https://github.com/NOAA-EMC/jcb-gdas/pull/61

have been merged into their respective `develop`, we need to update the GDASApp `develop` hash for `parm/jcb-gdas` to point at the new head, [`10a744a`](https://github.com/NOAA-EMC/jcb-gdas/commit/10a744aa2a8103e523aba54bebc44a965c2ec466) of jcb-gdas `develop`

Once this is done the `sorc/gdas.cd` hash in `ypwang19:feature/aero-varbc` needs to be updated to point at the new GDASApp `develop`.

2025-01-03 19:35 UTC, ypwang19 commented
> @ypwang19 , now that
> 
> * GDAS [Update jcb-base for aerosol VarBC GDASApp#1426](https://github.com/NOAA-EMC/GDASApp/pull/1426)
> * jcb-gdas [Update YAMLs for aerosol VarBC jcb-gdas#61](https://github.com/NOAA-EMC/jcb-gdas/pull/61)
> 
> have been merged into their respective `develop`, we need to update the GDASApp `develop` hash for `parm/jcb-gdas` to point at the new head, [`10a744a`](https://github.com/NOAA-EMC/jcb-gdas/commit/10a744aa2a8103e523aba54bebc44a965c2ec466) of jcb-gdas `develop`
> 
> Once this is done the `sorc/gdas.cd` hash in `ypwang19:feature/aero-varbc` needs to be updated to point at the new GDASApp `develop`.

I am not sure how to update the hash. 
Do we need to  open a PR in GDASApp and update the hash for the first step, then open a PR in global-workflow and update to the new GDASApp for the second step?

2025-01-03 19:47 UTC, CoryMartin-NOAA commented
@ypwang19 yes, I'll message you on Slack about how to do this.

2025-01-06 15:11 UTC, CoryMartin-NOAA commented
@ypwang19 could you update the values in https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.aeroanlgenb as part of this PR? The numbers in `develop` work at low resolution but are too slow at higher resolution. We should use what you and @andytangborn are using

2025-01-06 15:53 UTC, ypwang19 commented
> @ypwang19 could you update the values in https://github.com/NOAA-EMC/global-workflow/blob/develop/parm/config/gfs/config.aeroanlgenb as part of this PR? The numbers in `develop` work at low resolution but are too slow at higher resolution. We should use what you and @andytangborn are using

Sure, I just updated the numbers to what we are using.

2025-01-06 15:56 UTC, CoryMartin-NOAA commented
@ypwang19 thanks!

2025-01-06 15:57 UTC, CoryMartin-NOAA approved these changes, later dismissed

2025-01-08 06:00 UTC, WalterKolczynski-NOAA requested changes

2025-01-08 06:00 UTC, WalterKolczynski-NOAA commented on jobs/JGLOBAL_AERO_ANALYSIS_INITIALIZE
> +    COM_CHEM_ANALYSIS_PREV:COM_CHEM_ANALYSIS_TMPL
Variable should designate whether it is an in or an out. Since this is pointing to a previous cycle, I'm assuming an input.
```suggestion
    COMIN_CHEM_ANALYSIS_PREV:COM_CHEM_ANALYSIS_TMPL
```

2025-05-13 15:36 UTC, closed without merging