update the following files with "python3" in shebang
NOAA-EMC/global-workflow pull request #497
Opened 2021-11-12 17:52 UTC by JianKuang-UMD

2021-11-12 18:02 UTC, WalterKolczynski-NOAA requested changes
Code looks fine, but there's no commit message for the PR and the title needs work.

2021-11-12 19:19 UTC, WalterKolczynski-NOAA commented
Please compare this title and commit message with the issue that it is fixing. The issue has a description of _why_ the change is being made. Commit messages are supposed to describe the why as well. We can tell the what by looking at the diff, the commit needs to tell us why we bothered.

The title should begin with a capital letter, and the grammar is ambiguous; it can be read as you updated files that _had_ python3 in the shebang, rather than updating them so they now have it.

2021-11-16 14:01 UTC, JianKuang-UMD commented
@WalterKolczynski-NOAA Does it looks OK now?

2021-11-16 15:10 UTC, WalterKolczynski-NOAA commented
Much better

2021-11-16 15:10 UTC, WalterKolczynski-NOAA approved these changes

2021-11-16 15:11 UTC, merged