Stop archiving gfsarch.log as it is being written
NOAA-EMC/global-workflow pull request #581
Opened 2022-01-14 07:38 UTC by WalterKolczynski-NOAA

The gfs archive job was failing because it was attempting to archive its own log file into gfsa.tar while it was being written. To exclude that file pattern, bash extended globbing is turned on, which allows the use of a negating group.

Fixes: #558

2022-01-14 07:39 UTC, WalterKolczynski-NOAA commented
@DavidHuber-NOAA Can you test this on one of your failures so I don't have to run several cycles just to test this?

2022-01-14 14:17 UTC, DavidHuber-NOAA requested changes
This isn't working for me on S4.  Since these are `ksh` scripts, shopt is not a valid command.  However, extended globbing should already be part of the available syntax in `ksh`.  I've verified this on the terminal, so I'm not sure why it fails in the script.  I've uploaded the log file to Hera: /scratch1/NESDIS/nesdis-rdo2/David.Huber/s4_logs/384_p8a/gfsarch.log.

2022-01-14 15:01 UTC, aerorahul commented
@WalterKolczynski-NOAA 
We want to know exactly what is being archived.
Globbing can lead to archiving stale or irrelevant files or remnants.

2022-01-18 18:14 UTC, aerorahul approved these changes
Since this is a bugfix, I am fine with this change.
@WalterKolczynski-NOAA 
Mind if you change the interpreter in `ush/hpssarch_gen.sh` to `#/bin/bash` instead of `ksh`?

2022-02-02 02:35 UTC, WalterKolczynski-NOAA commented
@DavidHuber-NOAA I changed the shell for the archive job to bash and it solves the problem for me on Hera. Please confirm it works for you.

2022-02-02 13:34 UTC, DavidHuber-NOAA commented
> @DavidHuber-NOAA I changed the shell for the archive job to bash and it solves the problem for me on Hera. Please confirm it works for you.

@WalterKolczynski-NOAA Yes, it works for me now.  Thanks!

2022-02-02 13:34 UTC, DavidHuber-NOAA approved these changes
This works for me now.

2022-02-02 16:19 UTC, merged