Exception handling fix in JGFS_ATMOS_CYCLONE_TRACKER to handle ${USHens_tracker}/data_check_gfs.sh return code
NOAA-EMC/global-workflow pull request #642
Opened 2022-02-09 17:43 UTC by lgannoaa

Implement exception handling in JGFS_ATMOS_CYCLONE_TRACKER to handle error code return from ${USHens_tracker}/data_check_gfs.sh

Fix: #507

**Description**
${USHens_tracker}/data_check_gfs.sh return error code if required file not found.
However, jjob JGFS_ATMOS_CYCLONE_TRACKER does not handle this exception and continue process with this silent fail.
Exception handling code is now included.

**Type of change**

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

**How Has This Been Tested?**

  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

2022-02-09 22:16 UTC, WalterKolczynski-NOAA requested changes, later dismissed
Might need more information about the error codes (particularly 6) from data_check_gfs.sh to make this decision.

2022-02-09 22:16 UTC, WalterKolczynski-NOAA commented on jobs/JGFS_ATMOS_CYCLONE_TRACKER
> +export err=$?; err_chk
Should code 6 still be ignored? If the comment is correct, I don't know that we want to fail the job if data of opportunity is missing but everything else is correct.

2022-03-22 16:44 UTC, WalterKolczynski-NOAA commented on jobs/JGFS_ATMOS_CYCLONE_TRACKER
> +export err=$?; err_chk
Can I get an answer to this so we can get this PR in

2022-03-22 17:07 UTC, lgannoaa commented on jobs/JGFS_ATMOS_CYCLONE_TRACKER
> +export err=$?; err_chk
Code 6 here is not consider as failure. It can be ignored to make exception handling effective.

2022-03-22 17:09 UTC, WalterKolczynski-NOAA commented on jobs/JGFS_ATMOS_CYCLONE_TRACKER
> +export err=$?; err_chk
Okay, this needs to be updated then to retain that from the previous code.

2022-04-05 15:02 UTC, aerorahul commented
Any progress on this PR?

2022-04-05 15:07 UTC, lgannoaa commented
I provided my solution. Do you still have any question @WalterKolczynski-NOAA ?

2022-04-05 15:20 UTC, aerorahul commented
@lgannoaa 
The original script exits only if error code is 6.
The change implies all error codes (except 0) will cause an exit.  I think that is reasonable.

I also note that https://github.com/NOAA-EMC/global-workflow/blob/fc6e1c3316397432d2da218b3c4fc0ea1fe70644/jobs/JGFS_ATMOS_CYCLONE_TRACKER#L131
does the check this script was performing.  Would an `exit 6` be appropriate for the above line instead of just `exit`?

2022-04-05 15:25 UTC, lgannoaa commented
@aerorahul, exit code 6 cause job to fail. Therefore, job should fail. Hence my PR to modify it.

2022-04-05 15:27 UTC, aerorahul approved these changes
looks good

2022-04-05 15:27 UTC, aerorahul commented on jobs/JGFS_ATMOS_CYCLONE_TRACKER
> +export err=$?; err_chk
I think this works.

2022-04-12 14:50 UTC, WalterKolczynski-NOAA approved these changes

2022-04-20 01:22 UTC, merged