Feature/ecflow suite generator
NOAA-EMC/global-workflow pull request #704
Opened 2022-03-30 19:06 UTC by KyleNevins-NOAA

**Description**
This PR is to merge in the workflow generator application that uses a YAML file to create suite definition files for ecflow. 

**Type of change**
- [X] New feature (non-breaking change which adds functionality)
- [X] This change requires a documentation update

**How Has This Been Tested?**
To test: 
1. Change into the workflow directory: ` cd global-workflow/workflow_generator`
1. Ensure the YAML file is configured with the suites/tasks that are wanted. 
1. Run the utility: `python3 setup_workflow.py --expdir ../parm/config`

** Remaining items **
1. Additional documentation
1. Code documentation
1. Test suite with existing production ecflow definition file.

2022-04-14 18:01 UTC, WalterKolczynski-NOAA requested changes
Looks good in general, except it is lacking in documentation and doesn't appear to follow PEP8. I don't think it is too far off PEP8 and I haven't run a linter yet, but I know there's supposed to be a space after commas, for example.

2022-04-18 19:14 UTC, KyleNevins-NOAA commented
> Looks good in general, except it is lacking in documentation and doesn't appear to follow PEP8. I don't think it is too far off PEP8 and I haven't run a linter yet, but I know there's supposed to be a space after commas, for example.

Have made some adjustments to two of the modules but more documentation/pep8/readme updates incoming.

2022-04-20 19:21 UTC, KyleNevins-NOAA commented
Added in additional documentation within the code, I believe all methods, classes, and program descriptions are now documented. Also updated the readme.

2022-04-27 18:04 UTC, WalterKolczynski-NOAA requested changes
Descriptions look great. For consistency, I think we should have a Parameters and Returns for every method, even if we just put None in the category.

2022-04-27 18:04 UTC, WalterKolczynski-NOAA commented on workflow_generator/ecflow_setup/ecflow_definitions.py
> +            addTrigger = ecflow.Trigger(addtrigger.get_expression(), operand)
left side is still using camelcase (should all these be snake case, i.e. add_trigger)?

2022-04-27 18:04 UTC, WalterKolczynski-NOAA commented on workflow_generator/ecflow_setup/ecflow_definitions.py
>      def set_initial_max_value(self,range_token):
Missing space after comma

2022-04-27 18:04 UTC, WalterKolczynski-NOAA commented on workflow_generator/ecflow_setup/ecflow_definitions.py
>      def set_initial_max_value(self,range_token):
Missing space after comma

2022-04-27 18:04 UTC, WalterKolczynski-NOAA commented on workflow_generator/ecflow_setup/ecflow_definitions.py
> +        Returns the name of the node.
I know it seems redundant/silly, but this and the next few methods should have a Returns section for consistency (especially once we start using a documentation generator to turn these blocks into documentation)

2022-04-27 18:04 UTC, WalterKolczynski-NOAA commented on workflow_generator/ecflow_setup/ecflow_definitions.py
> +        Returns the name of the node.
I know it seems redundant/silly, but this and the next few methods should have a Returns section for consistency (especially once we start using a documentation generator to turn these blocks into documentation)

2022-04-27 18:04 UTC, WalterKolczynski-NOAA commented on workflow_generator/ecflow_setup/ecflow_definitions.py
> +7
Erroneous 7?

2022-04-27 18:04 UTC, WalterKolczynski-NOAA commented on workflow_generator/ecflow_setup/ecflow_definitions.py
> +7
Erroneous 7?

2022-04-28 15:10 UTC, KyleNevins-NOAA commented on workflow_generator/ecflow_setup/ecflow_definitions.py
> +            addTrigger = ecflow.Trigger(addtrigger.get_expression(), operand)
Using snake case now. If you see any others, please let me know and I'll adjust.

2022-04-28 15:11 UTC, KyleNevins-NOAA commented on workflow_generator/ecflow_setup/ecflow_definitions.py
>      def set_initial_max_value(self,range_token):
Shoot, thought I got them all, was bound to miss one or two. Thanks, fixed it up.

2022-04-28 15:11 UTC, KyleNevins-NOAA commented on workflow_generator/ecflow_setup/ecflow_definitions.py
> +        Returns the name of the node.
Added in a RETURNS or PARAMETERS section to all of the methods. Added value NONE if there wasn't actually something for that section.

2022-04-28 15:11 UTC, KyleNevins-NOAA commented on workflow_generator/ecflow_setup/ecflow_definitions.py
> +7
Yeah, not sure how that got there. Lucky number 7 has been removed.

2022-05-04 15:43 UTC, WalterKolczynski-NOAA approved these changes

2022-05-09 17:08 UTC, merged