Improve the getic.sh to retrive restart files for warm start for GEFS
NOAA-EMC/global-workflow pull request #921
Opened 2022-07-20 18:58 UTC by XianwuXue-NOAA

**Description**

This PR includes two sets of changes related to merging GEFS into the GFS system:
1) Change the DATA to include jobid to avoid different members using same DATA
2) Add new features to retrieve GFS and ensemble members restart files and stage them in the appropriate directories

**Type of change**

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

**How Has This Been Tested?**

The script was tested on Hera.

  
**Checklist**

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code

Refs: #911

2022-07-21 19:49 UTC, aerorahul requested changes
In principle the changes are fine.
A few minor comments apart from those in the review:
- remove the `echo` where unnecessary and all the `ls` statements.
- module loads need to go out from this script

A major comment:
- a lot of the code is duplicated.  Can we work to reduce that?

2022-07-21 19:49 UTC, aerorahul commented on jobs/rocoto/getic.sh
> +            module load nco/4.9.3
The `nco` module is loaded in `module_base.$target`.

2022-07-21 19:49 UTC, aerorahul commented on jobs/rocoto/getic.sh
> +            module load nco/4.9.3
same comment as above.

2022-07-21 19:49 UTC, aerorahul commented on jobs/rocoto/getic.sh
> +                sgrp=1
seems like this can be reduced to `cmem/10` and/or `cmem%10` rather than this big `if-else` block.

2022-07-21 20:13 UTC, XianwuXue-NOAA commented on jobs/rocoto/getic.sh
> +            module load nco/4.9.3
OK, I will delete this line.

2022-07-21 20:13 UTC, XianwuXue-NOAA commented on jobs/rocoto/getic.sh
> +            module load nco/4.9.3
No problem. I will delete this one.

2022-07-21 20:15 UTC, XianwuXue-NOAA commented
@aerorahul I am working on reducing the duplicated statements?

2022-07-22 12:56 UTC, XianwuXue-NOAA commented
@aerorahul I have modified the script and pushed to this PR

2022-08-30 22:24 UTC, closed without merging